export const adminPage = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>知流 · Knowledge Relay</title>
  <style>
    :root { color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"PingFang SC",sans-serif;--green:#41e6b2;--cyan:#62c8ff;--violet:#9b8cff;--ink:#eaf7f2;--muted:#8ea9a0;--line:#203c35;--soft:#102720; }
    * { box-sizing:border-box; } html{scrollbar-gutter:stable;background:#06110d} body { margin:0;background-image:linear-gradient(#52e2bb0c 1px,transparent 1px),linear-gradient(90deg,#52e2bb0c 1px,transparent 1px),radial-gradient(circle at 82% 0,#123f48 0,transparent 38%),radial-gradient(circle at 8% 88%,#113a2e 0,transparent 34%);background-size:42px 42px,42px 42px,auto,auto;background-color:#06110d;color:var(--ink);min-height:100vh;overflow-x:hidden; }
    button,input,textarea,select { font:inherit; } button { cursor:pointer;transition:border-color .16s ease,background-color .16s ease,filter .16s ease; } button:hover{filter:brightness(1.06)}button:disabled { cursor:wait;opacity:.68;filter:none; }
    .hidden { display:none!important; } .shell { min-height:100vh; display:grid; grid-template-columns:230px minmax(0,1fr);isolation:isolate; }
    aside { position:relative;background:#071713f7;border-right:1px solid #2b514566;color:white;padding:28px 18px;display:flex;flex-direction:column;gap:24px;box-shadow:18px 0 60px #0003; }
    aside:after{content:"";position:absolute;right:-1px;top:24px;width:1px;height:120px;background:linear-gradient(transparent,var(--green),transparent);filter:drop-shadow(0 0 6px var(--green))}
    .brand { padding:0 10px; }.brand strong { display:block;font-size:23px;letter-spacing:.14em;background:linear-gradient(90deg,var(--green),var(--cyan));-webkit-background-clip:text;color:transparent;filter:drop-shadow(0 0 16px #41e6b238) }.brand span { color:#71968a;font-size:10px;letter-spacing:.22em;text-transform:uppercase; }
    nav { display:grid; gap:6px; } nav button { display:flex;gap:10px;align-items:center;text-align:left;border:1px solid transparent;background:transparent;color:#b9d0c7;padding:11px 12px;border-radius:11px; }
    nav button i{font-style:normal;color:#5e8779;font-size:12px}nav button.active,nav button:hover { color:#eafff7;border-color:#2b51454d;background:linear-gradient(90deg,#41e6b21d,#62c8ff08);box-shadow:inset 2px 0 var(--green),0 8px 24px #0003; }
    .account { margin-top:auto;padding:12px 10px;border-top:1px solid #ffffff1f;font-size:13px;color:#b8d0c5; }
    main { position:relative;padding:38px;max-width:none;width:100%;overflow:hidden; } main:before{content:"";position:absolute;z-index:-1;width:360px;height:360px;right:3vw;top:90px;border:1px solid #62c8ff22;border-radius:50%;background:conic-gradient(from 45deg,transparent,#41e6b21d,transparent 36%,#62c8ff17,transparent 70%);opacity:.72;pointer-events:none;animation:ambient-orbit 22s linear infinite;will-change:transform}@keyframes ambient-orbit{to{transform:rotate(360deg)}} h1 { margin:0;font-size:clamp(28px,3vw,38px);letter-spacing:-.035em; } h2 { margin:0 0 15px;font-size:19px; } p { line-height:1.65; }
    [data-view]:not(.hidden){animation:page-in .35s ease both}@keyframes page-in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}.page-kicker{display:block;margin-bottom:8px;color:var(--green);font:700 10px/1 ui-monospace,monospace;letter-spacing:.2em;text-transform:uppercase}.hero-title{background:linear-gradient(110deg,#f0fff9 20%,#82eac9 55%,#6ecbff);-webkit-background-clip:text;color:transparent;text-shadow:0 0 50px #41e6b21c}
    .head { display:flex;justify-content:space-between;align-items:center;margin-bottom:26px;gap:20px; }
    .muted { color:var(--muted); } .grid { display:grid;grid-template-columns:repeat(4,1fr);gap:14px; }
    .card { position:relative;background:linear-gradient(145deg,#10241ef5,#081713fa);border:1px solid var(--line);border-radius:17px;padding:20px;box-shadow:0 18px 48px #0006,inset 0 1px #ffffff0a;transition:border-color .18s ease; }.card:hover{border-color:#2d5b4c}
    .metric { position:relative;overflow:hidden }.metric:after{content:"";position:absolute;width:70px;height:70px;right:-25px;top:-25px;background:var(--green);filter:blur(35px);opacity:.18}.metric strong { display:block;font-size:32px;margin-top:8px;color:var(--green);font-variant-numeric:tabular-nums; }.metric span { color:var(--muted);font-size:12px;letter-spacing:.08em; }
    .section { margin-top:18px; }.row { display:flex;gap:10px;align-items:center;flex-wrap:wrap; }
    .spread { display:flex;justify-content:space-between;gap:12px;align-items:center; }.stack { display:grid;gap:12px; }
    input,textarea,select { width:100%;border:1px solid #27473d;border-radius:10px;padding:12px 13px;background:#06140f;color:var(--ink); }
    input:focus,textarea:focus,select:focus{outline:0;border-color:var(--green);box-shadow:0 0 0 3px #41e6b218,0 0 24px #41e6b210} textarea { min-height:110px;resize:vertical; } label { display:grid;gap:6px;font-size:13px;color:#91afa4; }
    .check { display:flex;align-items:center;gap:8px; }.check input { width:auto; }
    .primary,.secondary,.danger,.button-link { border:0;border-radius:9px;padding:10px 15px; }
    .primary { color:#04110c;background:linear-gradient(135deg,var(--green),#5bd6e9);font-weight:750;box-shadow:0 9px 28px #41e6b22c }.primary:hover{box-shadow:0 12px 36px #41e6b247}.secondary { color:#cfe8df;background:#153229;border:1px solid #294e42; }.danger { color:#ffaaa3;background:#49221f; }
    .small { padding:7px 10px;font-size:13px; }.pill { border-radius:99px;padding:4px 8px;font-size:11px;background:#17342b;color:#9bbcaf;border:1px solid #25463b }.pill.ok { background:#103b2c;color:#55e6a8;border-color:#23704f }.pill.warn { background:#433716;color:#f3cf63;border-color:#6c5924 }
    .button-link{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;color:#04110c;background:linear-gradient(135deg,var(--green),#5bd6e9);font-weight:700;box-shadow:0 8px 22px #41e6b225}
    .list { display:grid;gap:10px; }.item { padding:15px;border:1px solid var(--line);border-radius:11px;background:#0c1d17f2;transition:border-color .16s ease,background-color .16s ease; }.message { cursor:pointer; }.message:hover { border-color:#3c8d72;background:#10241d }.message .text { color:#9db8ae;margin-top:8px;white-space:pre-wrap;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden; }
    .empty { text-align:center;padding:44px;color:var(--muted); }.notice { border:1px solid #285344;border-radius:12px;padding:12px 14px;background:#102d23;color:#7ae7ba;margin-bottom:14px;white-space:pre-wrap;box-shadow:0 10px 35px #0004 }.error { background:#3b1e1c;color:#ffaaa3;border-color:#6c302d }.token { display:block;padding:12px;background:#04100c;color:#79eaba;border:1px solid #244a3c;border-radius:8px;word-break:break-all;font-family:ui-monospace,monospace;font-size:12px; }.skill-source-info{padding:13px;border:1px solid #2a5548;border-radius:10px;background:#0c241c;color:#b7d6ca;font-size:13px;line-height:1.65}.skill-source-info strong{color:var(--green)}
    .provider-console{overflow:hidden;background:radial-gradient(circle at 90% 0,#17605a40,transparent 34%),linear-gradient(145deg,#0e251ef8,#071511fc)}.provider-console:after{content:"";position:absolute;width:220px;height:220px;border:1px solid #41e6b21f;border-radius:50%;right:-100px;top:-130px;box-shadow:0 0 56px #41e6b210}.provider-head{display:flex;align-items:center;gap:14px;margin-bottom:18px}.provider-orb{position:relative;width:44px;height:44px;border-radius:50%;border:1px solid #4ce9ba88;background:radial-gradient(circle at 35% 32%,#d8fff2,var(--green) 8%,#123b30 34%,#06110d 67%);box-shadow:0 0 26px #41e6b233}.provider-orb:after{content:"";position:absolute;inset:-6px;border-radius:50%;border:1px dashed #62c8ff55;animation:orbital-spin 12s linear infinite;will-change:transform}@keyframes orbital-spin{to{transform:rotate(360deg)}}.provider-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.provider-grid .wide{grid-column:1/-1}.provider-status{display:flex;align-items:center;gap:7px;font:600 11px/1.4 ui-monospace,monospace;color:#75e8bd}.provider-status:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green);animation:status-pulse 2.2s ease-in-out infinite;will-change:opacity,transform}@keyframes status-pulse{50%{opacity:.48;transform:scale(.72)}}.secret-hint{font-size:11px;color:#6f988a}.oauth-panel{padding:14px;border:1px solid #3d4e71;border-radius:12px;background:linear-gradient(135deg,#151c36,#0b1a1a)}.model-picker{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.model-picker .secondary{white-space:nowrap}.model-catalog-hint{display:flex;align-items:center;min-height:17px;color:#72998b;font-size:11px}.model-catalog-hint.loading:before{content:"";width:7px;height:7px;margin-right:7px;border-radius:50%;background:var(--cyan);box-shadow:0 0 10px var(--cyan);animation:status-pulse 1s ease-in-out infinite}
    .strategy-card{background:radial-gradient(circle at 0 100%,#1750402e,transparent 35%),linear-gradient(145deg,#10241ed9,#081713ed)}.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:18px}.section-head h2{margin-bottom:6px}.setting-switch{display:grid;grid-template-columns:auto 1fr;gap:10px 12px;align-items:start;padding:14px;border:1px solid #23443a;border-radius:12px;background:#081a14}.setting-switch input{width:auto;margin-top:3px}.setting-switch strong{display:block;color:#dff8ee}.setting-switch span{display:block;margin-top:3px;color:var(--muted);font-size:12px;line-height:1.55}.strategy-fields{display:grid;gap:12px}.form-actions{display:flex;justify-content:flex-end;padding-top:2px}.advanced{border:1px solid #203e35;border-radius:11px;background:#071610;overflow:hidden}.advanced summary{cursor:pointer;padding:12px 14px;color:#84aa9d;font-size:12px;list-style:none}.advanced summary::-webkit-details-marker{display:none}.advanced summary:after{content:"＋";float:right;color:var(--green)}.advanced[open] summary:after{content:"－"}.advanced-body{padding:0 14px 14px}.advanced-body label{font-size:12px}.advanced-body input{color:#73978b;background:#05100c}
    .skill-list{gap:12px}.skill-card{position:relative;overflow:hidden;padding:18px 18px 18px 20px;border-radius:15px;background:radial-gradient(circle at 100% 0,#1a554336,transparent 34%),linear-gradient(145deg,#10241ed9,#081713ed);box-shadow:0 14px 42px #0005,inset 0 1px #ffffff09}.skill-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:2px;background:linear-gradient(var(--green),var(--cyan));box-shadow:0 0 12px var(--green)}.skill-card .spread{align-items:flex-start}.skill-main{min-width:0;flex:1}.skill-title-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.skill-title-row>strong{display:flex;align-items:center;font-size:15px}.skill-description{margin:7px 0 0;line-height:1.55}.skill-actions{flex-wrap:nowrap;align-self:center}.skill-code{font:11px/1.5 ui-monospace,monospace;color:#608f80;margin-top:7px}.skill-symbol{display:inline-grid;place-items:center;width:26px;height:26px;border-radius:8px;background:#173a30;color:var(--green);margin-right:8px;box-shadow:inset 0 0 12px #41e6b210}
    .auth { min-height:100vh;display:grid;place-items:center;padding:22px;background:radial-gradient(circle at 20% 0,#154d42,transparent 42%),radial-gradient(circle at 90% 80%,#143348,transparent 38%),#06110d; }.auth .card { width:min(440px,100%);padding:30px; }.tabs { display:flex;gap:5px;background:var(--soft);padding:4px;border-radius:10px;margin-bottom:20px; }.tabs button { flex:1;border:0;background:transparent;color:var(--muted);padding:8px;border-radius:7px; }.tabs button.active { background:#17372d;color:var(--ink);box-shadow:0 2px 8px #0004; }
    dialog { width:min(760px,92vw);border:1px solid #2d5145;border-radius:15px;padding:0;background:#0a1a15;color:var(--ink);box-shadow:0 26px 100px #000b; } dialog::backdrop { background:#020906e8 }.dialog-body { padding:24px; }.markdown { white-space:pre-wrap;background:#06120e;padding:14px;border:1px solid #1d382f;border-radius:9px;max-height:45vh;overflow:auto;font:13px/1.6 ui-monospace,monospace; }
    .sync-live{display:inline-flex;align-items:center;gap:7px;color:#79a799;font-size:12px}.sync-live:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green)}.attachments{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px;margin-top:14px}.attachment{padding:12px;border:1px solid #25453a;border-radius:10px;background:#07150f}.attachment strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attachment-actions{display:flex;gap:7px;margin-top:9px}.attachment-actions a{text-decoration:none}.preview-frame{width:100%;height:min(65vh,680px);border:0;background:white;border-radius:9px;margin-top:12px}.preview-image{display:block;max-width:100%;max-height:65vh;margin:12px auto 0;border-radius:9px}
    #qr { width:280px;height:280px;max-width:75vw;display:block;margin:auto; }
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;scroll-behavior:auto!important;transition-duration:.01ms!important}}
    @media(max-width:800px){.shell{display:block}.shell aside{position:sticky;top:0;z-index:3;padding:12px}.brand,.account{display:none}nav{display:flex;overflow:auto}nav button{white-space:nowrap}main{padding:20px}.grid{grid-template-columns:repeat(2,1fr)}.provider-grid{grid-template-columns:1fr}.provider-grid .wide{grid-column:auto}.head{align-items:flex-start}.skill-card .spread{display:grid}.skill-actions{justify-self:start}.section-head{display:grid}.form-actions .primary{width:100%}}
  </style>
</head>
<body>
  <div id="auth" class="auth hidden"><section class="card">
    <h1>知流 · Knowledge Relay</h1><p class="muted" id="authLead">把微信中的碎片，汇入你的知识系统。</p>
    <div id="authNotice"></div>
    <form id="authForm" class="stack">
      <label id="displayLabel" class="hidden">显示名称<input id="displayName" autocomplete="name" /></label>
      <label>密码<input id="password" type="password" minlength="8" autocomplete="current-password" required /></label>
      <button id="authSubmit" class="primary" type="submit">登录</button>
    </form>
  </section></div>

  <div id="app" class="shell hidden">
    <aside><div class="brand"><strong>知流</strong><span>Knowledge Relay</span></div>
      <nav>
        <button data-page="home" class="active"><i>01</i>概览</button><button data-page="messages"><i>02</i>收件箱</button><button data-page="wechat"><i>03</i>微信连接</button><button data-page="sync"><i>04</i>Obsidian 同步</button><button data-page="agent"><i>05</i>AI Agent</button><button data-page="skills"><i>06</i>Skills</button>
      </nav>
      <div class="account"><div id="accountName"></div><button id="logout" class="secondary small" style="margin-top:9px">退出登录</button></div>
    </aside>
    <main>
      <div id="globalNotice"></div>
      <section data-view="home"><div class="head"><div><h1>知识流概览</h1><p class="muted">从微信捕获，经规则或 AI 整理，可靠汇入 Obsidian。</p><span id="liveStatus" class="sync-live">实时监听新消息</span></div><button class="primary" data-go="wechat">连接微信</button></div>
        <div class="grid"><div class="card metric"><span>全部消息</span><strong id="mMessages">0</strong></div><div class="card metric"><span>待同步</span><strong id="mPending">0</strong></div><div class="card metric"><span>微信账号</span><strong id="mBots">0</strong></div><div class="card metric"><span>同步设备</span><strong id="mTargets">0</strong></div></div>
        <div class="card section"><h2>最近消息</h2><div id="recentMessages" class="list"></div></div>
        <div class="card section"><h2>账户安全</h2><form id="passwordForm" class="row"><input id="currentPassword" type="password" minlength="8" placeholder="当前密码" required style="flex:1" /><input id="newPassword" type="password" minlength="8" placeholder="新密码（至少 8 位）" required style="flex:1" /><button class="secondary" type="submit">修改密码</button></form></div>
      </section>
      <section data-view="messages" class="hidden"><div class="head"><div><h1>知识收件箱</h1><p class="muted">“已归档”表示主 Obsidian 设备已经确认写入成功。</p><span id="messagesLive" class="sync-live">自动刷新中</span></div><button id="refreshMessages" class="secondary">立即刷新</button></div><div id="messagesList" class="list"></div></section>
      <section data-view="wechat" class="hidden"><div class="head"><div><h1>微信连接</h1><p class="muted">连接你自己的 iLink Bot，知流只接收扫码账号本人的消息。</p></div><button id="connectWechat" class="primary">添加微信</button></div><div id="accountsList" class="list"></div></section>
      <section data-view="sync" class="hidden"><div class="head"><div><h1>Obsidian 同步</h1><p class="muted">为每个 Vault 创建设备令牌。令牌只显示一次，请复制到插件设置。</p></div></div>
        <div class="card"><div class="spread"><div><h2>知流同步插件</h2><p class="muted">下载后解压到 Vault 的 .obsidian/plugins/wechat-ilink-inbox-sync，并在 Obsidian 中启用。</p></div><a class="button-link" href="/downloads/knowledge-relay-obsidian.zip" download>下载插件</a></div></div>
        <div class="card"><h2>创建同步设备</h2><form id="syncForm" class="stack"><label>设备或 Vault 名称<input id="syncName" value="我的 Obsidian" required /></label><label>默认收件箱目录<input id="syncFolder" value="Inbox/微信" required /></label><label class="check"><input id="syncPrimary" type="checkbox" checked />作为主同步设备</label><button class="primary" type="submit">生成连接令牌</button></form><div id="syncTokenResult" class="hidden" style="margin-top:14px"><p>请立即复制，离开页面后无法再次查看：</p><code id="syncToken" class="token"></code></div></div>
        <div class="card section"><h2>已连接设备</h2><div id="targetsList" class="list"></div></div>
      </section>
      <section data-view="agent" class="hidden"><div class="head"><div><span class="page-kicker">Agent Runtime / Control Plane</span><h1 class="hero-title">Nanobot 智能处理引擎</h1><p class="muted">在这里配置 Nanobot 的模型提供者。知流只提交收件任务，不会绕过 Runtime 直连模型。</p></div><button id="testAgent" class="secondary">运行链路测试</button></div>
        <div class="card provider-console"><div class="provider-head"><div class="provider-orb"></div><div><h2 style="margin:0">模型提供者</h2><div id="providerStatus" class="provider-status">正在读取 Runtime 配置</div></div></div>
          <form id="providerForm" class="provider-grid">
            <label>提供者<select id="providerSelect"></select></label>
            <label>模型标识<div class="model-picker"><input id="providerModel" list="providerModelOptions" maxlength="200" placeholder="输入或选择模型" required /><button id="refreshModels" class="secondary" type="button">刷新列表</button></div><datalist id="providerModelOptions"></datalist><span id="providerModelsHint" class="model-catalog-hint">保存凭据后，可由 Nanobot 在线读取模型列表。</span></label>
            <label id="providerBaseLabel" class="wide">API 地址<input id="providerBase" maxlength="1000" placeholder="https://.../v1" /></label>
            <label id="providerKeyLabel" class="wide">API Key<input id="providerKey" type="password" maxlength="2000" autocomplete="new-password" /><span id="providerKeyHint" class="secret-hint">密钥只写入 Nanobot 配置，页面不会回显。</span></label>
            <div id="providerOauthPanel" class="oauth-panel wide hidden"><strong>OpenAI Codex OAuth</strong><p class="muted">使用 OpenAI 账户授权 Nanobot。授权凭据由 Nanobot 保存，知流不读取令牌内容。</p><button id="providerOauth" class="secondary" type="button">连接 OpenAI 账户</button><div id="providerOauthHint" class="secret-hint" style="margin-top:8px"></div></div>
            <div class="spread wide"><span id="providerReloadHint" class="secret-hint"></span><button id="saveProvider" class="primary" type="submit">保存并重新加载 Runtime</button></div>
          </form>
        </div>
        <div class="card section strategy-card"><div class="section-head"><div><span class="page-kicker">Behavior / Preferences</span><h2>消息处理策略</h2><div class="muted">决定新消息是否交给 AI、如何整理，以及什么时候通过微信提醒你。</div></div><span class="pill ok">仅影响新消息</span></div><form id="agentForm" class="strategy-fields"><label class="setting-switch"><input id="agentEnabled" type="checkbox" /><span><strong>启用智能整理</strong><span>开启后由 Nanobot 选择 Skill，完成分类、摘要和附件生成；关闭后仍会保存原消息并同步到 Obsidian。</span></span></label><label>我的整理偏好<textarea id="agentInstructions" placeholder="例如：网页先总结核心观点；出现明确日期时提取为待办。"></textarea><span class="secret-hint">这是补充给 Nanobot 的长期偏好，不会替代每个 Skill 自己的规则。</span></label><label class="setting-switch"><input id="agentReply" type="checkbox" /><span><strong>允许回复普通消息</strong><span>只有 Agent 判断需要确认时才回复；普通收藏默认保持安静。</span></span></label><label class="setting-switch"><input id="agentFailureNotify" type="checkbox" checked /><span><strong>处理失败时微信提醒</strong><span>Nanobot 或模型不可用时，在当前消息下提醒；同类故障 6 小时内最多一次。</span></span></label><details class="advanced"><summary>高级连接信息</summary><div class="advanced-body"><label>Nanobot Runtime 内部地址<input id="agentBaseUrl" readonly /></label></div></details><div class="form-actions"><button class="primary" type="submit">保存处理策略</button></div></form></div>
      </section>
      <section data-view="skills" class="hidden"><div class="head"><div><span class="page-kicker">Workspace / Capabilities</span><h1 class="hero-title">Nanobot Skills</h1><p class="muted">管理 Nanobot 可以使用的能力，以及用于补充整理方式的提示规则。</p></div><button id="newSkill" class="primary">新增提示规则</button></div><div id="skillsList" class="list skill-list"></div></section>
    </main>
  </div>

  <dialog id="messageDialog"><div class="dialog-body"><div class="spread"><h2 id="dialogTitle"></h2><button class="secondary small" data-close>关闭</button></div><div id="dialogMeta" class="muted"></div><pre id="dialogMarkdown" class="markdown"></pre><div id="dialogAttachments" class="attachments"></div></div></dialog>
  <dialog id="previewDialog"><div class="dialog-body"><div class="spread"><h2 id="previewTitle">附件预览</h2><button class="secondary small" data-close>关闭</button></div><div id="previewBody"></div></div></dialog>
  <dialog id="qrDialog"><div class="dialog-body"><div class="spread"><h2>连接微信</h2><button class="secondary small" data-close>关闭</button></div><img id="qr" alt="微信登录二维码" /><p id="qrStatus" style="text-align:center">请用微信扫码并在手机上确认。</p><div id="pairWrap" class="row hidden"><input id="pairCode" inputmode="numeric" placeholder="输入微信显示的配对码" /><button id="submitPair" class="primary">提交</button></div></div></dialog>
  <dialog id="skillDialog"><div class="dialog-body"><div class="spread"><h2 id="skillDialogTitle">编辑 Skill</h2><button class="secondary small" data-close>关闭</button></div><form id="skillForm" class="stack"><input id="skillId" type="hidden" /><div id="skillSourceInfo" class="skill-source-info hidden"></div><label>名称<input id="skillName" maxlength="80" required /></label><label id="skillSlugLabel">标识<input id="skillSlug" maxlength="60" placeholder="例如 my-inbox-rule" required /></label><label>用途说明<textarea id="skillDescription" maxlength="500" required style="min-height:70px"></textarea></label><label><span id="skillContentLabel">Skill 规则</span><textarea id="skillContent" maxlength="20000" required style="min-height:260px"></textarea></label><label class="check"><input id="skillEnabled" type="checkbox" checked />启用这个 Skill</label><div class="row"><button class="primary" type="submit">保存</button><button id="deleteSkill" class="danger hidden" type="button">删除</button></div></form></div></dialog>

  <script>
    const $ = (selector) => document.querySelector(selector);
    const $$ = (selector) => Array.from(document.querySelectorAll(selector));
    let owner = null, dashboard = null, needsSetup = false, loginSession = null, polling = false, managedSkills = [], providerState = null, latestMessageSeq = 0, messageRefresh = null, modelCatalogRequest = 0;
    function escapeHtml(value) { const span=document.createElement('span');span.textContent=String(value==null?'':value);return span.innerHTML; }
    async function api(url, options) {
      const response = await fetch(url, Object.assign({ headers: {} }, options || {}, { headers: Object.assign({}, options && options.headers || {}, options && options.body ? {'Content-Type':'application/json'} : {}) }));
      const text = await response.text(); let data={}; try { data=text?JSON.parse(text):{}; } catch { data={error:text}; }
      if (!response.ok) throw new Error(data.error || ('请求失败：'+response.status)); return data;
    }
    function notice(message, error) { $('#globalNotice').innerHTML=message?'<div class="notice '+(error?'error':'')+'">'+escapeHtml(message)+'</div>':''; }
    function authNotice(message, error) { $('#authNotice').innerHTML=message?'<div class="notice '+(error?'error':'')+'">'+escapeHtml(message)+'</div>':''; }
    function configureAuth(setup) { needsSetup=setup;$('#displayLabel').classList.toggle('hidden',!setup);$('#authLead').textContent=setup?'首次使用，请设置个人账户。':'把微信中的碎片，汇入你的知识系统。';$('#authSubmit').textContent=setup?'创建个人账户':'登录'; }
    async function boot() {
      const bootstrap=await api('/api/bootstrap');
      try { const me=await api('/api/me'); owner=me.owner; showApp(); } catch { $('#auth').classList.remove('hidden');configureAuth(bootstrap.needsSetup); }
    }
    $('#authForm').addEventListener('submit',async event=>{event.preventDefault();authNotice('');try{const body=JSON.stringify({password:$('#password').value,displayName:$('#displayName').value});const result=await api(needsSetup?'/api/setup':'/api/login',{method:'POST',body});owner=result.owner;$('#auth').classList.add('hidden');showApp();if(result.migrated&&(result.migrated.account||result.migrated.messages))notice('已自动导入原有微信账号和 '+result.migrated.messages+' 条历史消息。');}catch(error){authNotice(error.message,true)}});
    const validPages=['home','messages','wechat','sync','agent','skills'];
    function pageFromLocation(){const page=location.hash.replace(/^#/,'');return validPages.includes(page)?page:'home';}
    async function showApp(){ $('#app').classList.remove('hidden');$('#accountName').textContent=owner.displayName+' · 个人版';await refreshAll();go(pageFromLocation(),false); }
    async function refreshAll(){ try{dashboard=await api('/api/dashboard');$('#mMessages').textContent=dashboard.messages;$('#mPending').textContent=dashboard.pendingSync;$('#mBots').textContent=dashboard.botAccounts;$('#mTargets').textContent=dashboard.syncTargets.length;renderAccounts();renderTargets();await loadMessages(true);await Promise.all([loadAgent(),loadProvider(),loadSkills()]);}catch(error){notice(error.message,true)} }
    function go(page,updateLocation=true){if(!validPages.includes(page))page='home';if(updateLocation&&location.hash!=='#'+page)history.pushState(null,'','#'+page);$$('[data-view]').forEach(v=>v.classList.toggle('hidden',v.dataset.view!==page));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='messages')loadMessages(true);}
    $$('[data-page]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.page)));$$('[data-go]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.go)));
    window.addEventListener('hashchange',()=>go(pageFromLocation(),false));
    $('#logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});
    $('#passwordForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/me/password',{method:'POST',body:JSON.stringify({currentPassword:$('#currentPassword').value,newPassword:$('#newPassword').value})});alert('密码已修改，请使用新密码重新登录。');location.reload();}catch(error){notice(error.message,true)}});
    async function loadMessages(silent){if(messageRefresh){await messageRefresh;if(!silent){$('#messagesLive').textContent='刷新完成 · '+new Date().toLocaleTimeString();notice('收件箱已刷新，当前没有遗漏。');}return;}const button=$('#refreshMessages');if(!silent){button.disabled=true;button.textContent='刷新中…';$('#messagesLive').textContent='正在刷新…';}messageRefresh=(async()=>{const result=await api('/api/messages?limit=100');const newest=result.messages[0]&&result.messages[0].seq||0;const hasNew=latestMessageSeq>0&&newest>latestMessageSeq;latestMessageSeq=Math.max(latestMessageSeq,newest);renderMessages(result.messages);const time=new Date().toLocaleTimeString();$('#messagesLive').textContent=hasNew?'发现新消息 · '+time:silent?'自动刷新中 · '+time:'刷新完成 · '+time;if(!silent)notice(hasNew?'已刷新并发现新消息。':'收件箱已刷新，当前没有新消息。');})().catch(error=>{if(!silent)notice('刷新失败：'+error.message,true);throw error;}).finally(()=>{messageRefresh=null;if(!silent){button.disabled=false;button.textContent='立即刷新';}});await messageRefresh;}
    function messageHtml(message){return '<article class="item message" data-message="'+escapeHtml(message.id)+'"><div class="spread"><strong>'+escapeHtml(message.title)+'</strong><div class="row"><span class="pill">'+escapeHtml(message.category)+'</span><span class="pill '+(message.archived?'ok':'warn')+'">'+(message.archived?'已归档':'待同步')+'</span></div></div><div class="muted">'+new Date(message.receivedAt).toLocaleString()+(message.attachmentCount?' · '+message.attachmentCount+' 个附件':'')+'</div><div class="text">'+escapeHtml(message.text||'（仅附件）')+'</div></article>';}
    function bindMessages(){ $$('[data-message]').forEach(item=>item.addEventListener('click',async()=>{const message=await api('/api/messages/'+encodeURIComponent(item.dataset.message));$('#dialogTitle').textContent=message.title;$('#dialogMeta').textContent=new Date(message.receivedAt).toLocaleString()+' · '+message.agentStatus;$('#dialogMarkdown').textContent=message.markdown;$('#dialogAttachments').innerHTML=(message.attachments||[]).map(a=>'<div class="attachment"><strong title="'+escapeHtml(a.fileName)+'">'+escapeHtml(a.fileName)+'</strong><div class="muted">'+escapeHtml(a.mimeType)+' · '+formatBytes(a.size)+'</div>'+(a.transcript?'<div class="muted">转写：'+escapeHtml(a.transcript)+'</div>':'')+'<div class="attachment-actions">'+(a.previewable?'<button class="secondary small" data-preview="'+a.id+'" data-name="'+escapeHtml(a.fileName)+'" data-mime="'+escapeHtml(a.mimeType)+'">预览</button>':'')+'<a class="secondary small" href="/api/attachments/'+a.id+'?download=1">下载</a></div></div>').join('');$$('[data-preview]').forEach(button=>button.addEventListener('click',()=>openPreview(button.dataset.preview,button.dataset.name,button.dataset.mime)));$('#messageDialog').showModal()})); }
    function formatBytes(value){const n=Number(value)||0;if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB';}
    function openPreview(id,name,mime){const url='/api/attachments/'+encodeURIComponent(id);$('#previewTitle').textContent=name;let html;if(mime.startsWith('image/'))html='<img class="preview-image" src="'+url+'" alt="'+escapeHtml(name)+'" />';else if(mime.startsWith('audio/'))html='<audio controls style="width:100%;margin-top:18px" src="'+url+'"></audio>';else if(mime.startsWith('video/'))html='<video controls class="preview-frame" src="'+url+'"></video>';else html='<iframe class="preview-frame" sandbox src="'+url+'"></iframe>';$('#previewBody').innerHTML=html;$('#previewDialog').showModal();}
    function renderMessages(messages){$('#messagesList').innerHTML=messages.length?messages.map(messageHtml).join(''):'<div class="card empty">还没有消息。连接微信后发一条消息试试。</div>';$('#recentMessages').innerHTML=messages.length?messages.slice(0,5).map(messageHtml).join(''):'<div class="empty">还没有消息</div>';bindMessages();}
    $('#refreshMessages').addEventListener('click',()=>loadMessages(false));
    function renderAccounts(){const accounts=dashboard.accounts;$('#accountsList').innerHTML=accounts.length?accounts.map(a=>'<div class="item spread"><div><strong>'+escapeHtml(a.botId)+'</strong><div class="muted">'+escapeHtml(a.ownerUserId||'未知微信用户')+' · '+(a.lastMessageAt?'最近消息 '+new Date(a.lastMessageAt).toLocaleString():'尚未收到消息')+'</div>'+(a.lastError?'<div class="muted">'+escapeHtml(a.lastError)+'</div>':'')+'</div><div class="row"><span class="pill '+(a.state==='running'?'ok':'warn')+'">'+escapeHtml(a.state==='running'?'接收中':a.state)+'</span><button class="danger small" data-remove-account="'+a.id+'">移除</button></div></div>').join(''):'<div class="card empty">尚未连接微信，请扫描二维码连接自己的机器人。</div>';$$('[data-remove-account]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('确定移除这个微信连接吗？历史消息不会删除。'))return;await api('/api/ilink/accounts/'+b.dataset.removeAccount,{method:'DELETE'});await refreshAll()}));}
    $('#connectWechat').addEventListener('click',async()=>{try{const result=await api('/api/ilink/login/start',{method:'POST'});loginSession=result.sessionId;$('#qr').src='/api/ilink/login/'+loginSession+'/qr.svg?x='+Date.now();$('#qrStatus').textContent='请用微信扫码并在手机上确认。';$('#pairWrap').classList.add('hidden');$('#qrDialog').showModal();pollLogin();}catch(error){notice(error.message,true)}});
    async function pollLogin(code){if(polling||!loginSession)return;polling=true;try{const result=await api('/api/ilink/login/'+loginSession+(code?'/verify':'/status'),code?{method:'POST',body:JSON.stringify({code})}:undefined);$('#qrStatus').textContent=result.message;$('#pairWrap').classList.toggle('hidden',result.status!=='need_verifycode');if(result.connected){$('#qrDialog').close();loginSession=null;await refreshAll();notice('微信连接成功，消息接收已经启动。');return;}if(result.status==='need_verifycode')return;if(['expired','error','verify_code_blocked','already_connected'].includes(result.status)){loginSession=null;return;}setTimeout(()=>pollLogin(),1000);}catch(error){$('#qrStatus').textContent=error.message;loginSession=null;}finally{polling=false}}
    $('#submitPair').addEventListener('click',()=>{const code=$('#pairCode').value.trim();if(code)pollLogin(code)});
    function renderTargets(){const targets=dashboard.syncTargets;$('#targetsList').innerHTML=targets.length?targets.map(t=>'<div class="item spread"><div><strong>'+escapeHtml(t.name)+'</strong> '+(t.primary?'<span class="pill ok">主设备</span>':'')+'<div class="muted">'+escapeHtml(t.folder)+' · 游标 '+t.lastAckSeq+(t.lastSeenAt?' · 最近同步 '+new Date(t.lastSeenAt).toLocaleString():'')+'</div></div><button class="danger small" data-revoke="'+t.id+'">撤销</button></div>').join(''):'<div class="empty">还没有 Obsidian 同步设备</div>';$$('[data-revoke]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('撤销后，这个插件将不能再同步。'))return;await api('/api/sync-targets/'+b.dataset.revoke,{method:'DELETE'});await refreshAll()}));}
    $('#syncForm').addEventListener('submit',async event=>{event.preventDefault();try{const result=await api('/api/sync-targets',{method:'POST',body:JSON.stringify({name:$('#syncName').value,folder:$('#syncFolder').value,primary:$('#syncPrimary').checked})});$('#syncToken').textContent=result.token;$('#syncTokenResult').classList.remove('hidden');await refreshAll();}catch(error){notice(error.message,true)}});
    async function loadAgent(){const s=await api('/api/agent/settings');$('#agentEnabled').checked=s.enabled;$('#agentBaseUrl').value=s.baseUrl;$('#agentInstructions').value=s.instructions;$('#agentReply').checked=s.autoReply;$('#agentFailureNotify').checked=s.notifyOnFailure!==false;}
    $('#agentForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/agent/settings',{method:'PUT',body:JSON.stringify({enabled:$('#agentEnabled').checked,baseUrl:$('#agentBaseUrl').value,instructions:$('#agentInstructions').value,autoReply:$('#agentReply').checked,notifyOnFailure:$('#agentFailureNotify').checked})});notice('Nanobot 处理设置已保存，之后的新消息会使用它。');}catch(error){notice(error.message,true)}});
    $('#testAgent').addEventListener('click',async()=>{const button=$('#testAgent');button.disabled=true;button.textContent='链路测试中…';try{const result=await api('/api/agent/test',{method:'POST'});notice(result.ok?'Nanobot、模型与 Agent Loop 链路正常。':'连接失败：'+result.error,!result.ok)}catch(error){notice(error.message,true)}finally{button.disabled=false;button.textContent='运行链路测试'}});
    function selectedProvider(){return providerState&&providerState.providers.find(item=>item.id===$('#providerSelect').value)}
    async function loadProviderModels(providerId){const requestId=++modelCatalogRequest,button=$('#refreshModels'),hint=$('#providerModelsHint');button.disabled=true;button.textContent='读取中…';hint.className='model-catalog-hint loading';hint.textContent='Nanobot 正在读取 '+(selectedProvider()?.name||providerId)+' 的在线模型目录…';try{const result=await api('/api/nanobot/provider/models?provider='+encodeURIComponent(providerId));if(requestId!==modelCatalogRequest)return;$('#providerModelOptions').innerHTML=(result.models||[]).map(model=>'<option value="'+escapeHtml(model.id)+'"'+(model.label?' label="'+escapeHtml(model.label)+'"':'')+'></option>').join('');hint.className='model-catalog-hint';if(result.status==='available')hint.textContent=result.modelCount?'已实时读取 '+result.modelCount+' 个模型 · '+new Date(result.fetchedAt*1000).toLocaleTimeString():'提供者返回了空模型列表，仍可手动填写模型标识。';else if(result.status==='not_configured')hint.textContent='请先保存这个提供者的凭据，再刷新模型列表。';else if(result.status==='unsupported')hint.textContent='这个提供者不支持在线模型目录，仍可手动填写。';else if(result.status==='missing_api_base')hint.textContent='请先保存 API 地址，再刷新模型列表。';else hint.textContent=result.message||'模型目录暂时不可用，仍可手动填写。';}catch(error){if(requestId!==modelCatalogRequest)return;$('#providerModelOptions').innerHTML='';hint.className='model-catalog-hint';hint.textContent='在线模型目录暂时不可用，仍可手动填写。';}finally{if(requestId===modelCatalogRequest){button.disabled=false;button.textContent='刷新列表'}}}
    function renderProviderFields(provider){if(!provider)return;const oauth=provider.auth==='oauth',local=provider.auth==='local';$('#providerBaseLabel').classList.toggle('hidden',oauth);$('#providerKeyLabel').classList.toggle('hidden',oauth||local);$('#providerOauthPanel').classList.toggle('hidden',!oauth);$('#saveProvider').classList.toggle('hidden',oauth);$('#providerOauth').disabled=oauth&&!providerState.oauthSupported;$('#providerOauthHint').textContent=oauth?(providerState.oauthSupported?'点击后会打开 OpenAI 官方授权页面。':'Docker/远程部署请在 Nanobot 容器终端完成 OAuth；也可以选择 OpenAI API Key。'):'';}
    async function loadProvider(){const state=await api('/api/nanobot/provider');providerState=state;const select=$('#providerSelect');select.innerHTML=state.providers.map(item=>'<option value="'+escapeHtml(item.id)+'">'+escapeHtml(item.name)+'</option>').join('');select.value=state.active.provider;$('#providerModel').value=state.active.model;$('#providerBase').value=state.active.apiBase;$('#providerKey').value='';$('#providerKey').placeholder=state.active.apiKeyConfigured?'已配置，留空保持不变':'输入该提供者的 API Key';$('#providerKeyHint').textContent=state.active.apiKeyConfigured?'凭据已配置。密钥不会返回浏览器，留空即可保持原值。':'密钥只写入 Nanobot 配置，页面不会回显。';$('#providerStatus').textContent=state.providers.find(item=>item.id===state.active.provider)?.name+' · '+state.active.model;$('#providerReloadHint').textContent=state.autoReload?'保存后 Runtime 会自动安全重载。':'保存后需要手动重启 Nanobot Runtime。';renderProviderFields(selectedProvider());loadProviderModels(state.active.provider);}
    $('#providerSelect').addEventListener('change',()=>{const provider=selectedProvider();if(!provider)return;$('#providerModel').value=provider.defaultModel||'';$('#providerBase').value=provider.defaultBaseUrl||'';$('#providerKey').value='';$('#providerKey').placeholder=provider.auth==='local'?'本地提供者无需密钥':'输入该提供者的 API Key';renderProviderFields(provider);loadProviderModels(provider.id)});
    $('#refreshModels').addEventListener('click',()=>loadProviderModels($('#providerSelect').value));
    $('#providerForm').addEventListener('submit',async event=>{event.preventDefault();const button=$('#saveProvider');button.disabled=true;button.textContent='保存配置中…';try{const result=await api('/api/nanobot/provider',{method:'PUT',body:JSON.stringify({provider:$('#providerSelect').value,model:$('#providerModel').value,apiBase:$('#providerBase').value,apiKey:$('#providerKey').value})});$('#providerStatus').textContent=result.autoReload?'Runtime 正在重新加载…':'配置已保存，等待手动重启';notice(result.autoReload?'模型配置已写入 Nanobot，Runtime 正在自动重新加载。':'模型配置已写入 Nanobot，请重启 Runtime 后测试。');setTimeout(()=>loadProvider().catch(()=>{}),2200)}catch(error){notice(error.message,true)}finally{button.disabled=false;button.textContent='保存并重新加载 Runtime'}});
    $('#providerOauth').addEventListener('click',async()=>{const button=$('#providerOauth');button.disabled=true;button.textContent='等待 OpenAI 授权…';try{await api('/api/nanobot/provider/openai-oauth',{method:'POST',body:JSON.stringify({model:$('#providerModel').value})});notice('OpenAI OAuth 授权成功，Nanobot 正在重新加载。');setTimeout(()=>loadProvider().catch(()=>{}),2200)}catch(error){notice('OAuth 授权失败：'+error.message,true)}finally{button.disabled=false;button.textContent='连接 OpenAI 账户'}});
    async function loadSkills(){const result=await api('/api/skills');managedSkills=result.skills;$('#skillsList').innerHTML=managedSkills.length?managedSkills.map(s=>'<article class="item skill-card"><div class="spread"><div class="skill-main"><div class="skill-title-row"><strong><span class="skill-symbol">'+(s.kind==='adapter'?'⌁':'✦')+'</span>'+escapeHtml(s.name)+'</strong><span class="pill">'+(s.kind==='adapter'?'Nanobot Skill':s.builtin?'内置规则':'自定义规则')+'</span>'+(s.customized?'<span class="pill warn">已修改</span>':'')+'<span class="pill '+(s.enabled?'ok':'')+'">'+(s.enabled?'已启用':'已停用')+'</span></div><div class="muted skill-description">'+escapeHtml(s.description)+'</div><div class="skill-code">'+escapeHtml(s.slug)+'</div></div><div class="row skill-actions"><button class="secondary small" data-skill-toggle="'+escapeHtml(s.id)+'">'+(s.enabled?'停用':'启用')+'</button><button class="secondary small" data-skill-edit="'+escapeHtml(s.id)+'">'+(s.kind==='adapter'?'编辑 Skill':'编辑规则')+'</button></div></div></article>').join(''):'<div class="card empty">还没有 Skill</div>';$$('[data-skill-edit]').forEach(b=>b.addEventListener('click',()=>openSkill(managedSkills.find(s=>s.id===b.dataset.skillEdit))));$$('[data-skill-toggle]').forEach(b=>b.addEventListener('click',async()=>{const s=managedSkills.find(x=>x.id===b.dataset.skillToggle);await api('/api/skills/'+encodeURIComponent(s.id),{method:'PUT',body:JSON.stringify({name:s.name,description:s.description,content:s.content,enabled:!s.enabled})});await loadSkills();notice((!s.enabled?'已启用：':'已停用：')+s.name+'。只影响之后收到的新消息。')}));}
    function openSkill(skill){const editing=Boolean(skill),adapter=editing&&skill.kind==='adapter';$('#skillDialogTitle').textContent=adapter?'编辑 Nanobot Skill':editing?'编辑 Skill':'新增自定义 Skill';$('#skillId').value=editing?skill.id:'';$('#skillName').value=editing?skill.name:'';$('#skillSlug').value=editing?skill.slug:'';$('#skillSlug').readOnly=editing;$('#skillSlugLabel').classList.toggle('hidden',editing);$('#skillDescription').value=editing?skill.description:'';$('#skillContent').value=editing?skill.content:'';$('#skillContentLabel').textContent=adapter?'Nanobot 实际加载的完整 SKILL.md':'Skill 规则';$('#skillEnabled').checked=editing?skill.enabled:true;$('#deleteSkill').classList.toggle('hidden',!editing);const sourceInfo=$('#skillSourceInfo');sourceInfo.classList.toggle('hidden',!adapter);sourceInfo.innerHTML=adapter?'<strong>这里就是 Runtime 实际加载的 Skill 内容。</strong><br>保存或停用会直接作用于 Nanobot workspace，只影响之后的新消息。':'';if(editing){$('#deleteSkill').textContent=skill.builtin?'恢复原版内容':'删除自定义 Skill';}$('#skillDialog').showModal();}
    $('#newSkill').addEventListener('click',()=>openSkill());
    $('#skillForm').addEventListener('submit',async event=>{event.preventDefault();try{const id=$('#skillId').value;const body=JSON.stringify({slug:$('#skillSlug').value,name:$('#skillName').value,description:$('#skillDescription').value,content:$('#skillContent').value,enabled:$('#skillEnabled').checked});await api(id?'/api/skills/'+encodeURIComponent(id):'/api/skills',{method:id?'PUT':'POST',body});$('#skillDialog').close();await loadSkills();notice('Skill 已保存，之后的新消息会使用最新规则。');}catch(error){notice(error.message,true)}});
    $('#deleteSkill').addEventListener('click',async()=>{const id=$('#skillId').value;if(!id)return;const skill=managedSkills.find(s=>s.id===id);if(!confirm(skill&&skill.builtin?'确定恢复这个系统 Skill 的默认内容和启用状态吗？':'确定删除这个自定义 Skill 吗？'))return;await api('/api/skills/'+encodeURIComponent(skill.builtin?'builtin:'+skill.slug:id),{method:'DELETE'});$('#skillDialog').close();await loadSkills();});
    $$('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
    setInterval(async()=>{if(!owner||document.hidden)return;try{const next=await api('/api/dashboard');const previous=dashboard&&dashboard.messages||0;dashboard=next;$('#mMessages').textContent=next.messages;$('#mPending').textContent=next.pendingSync;$('#mBots').textContent=next.botAccounts;$('#mTargets').textContent=next.syncTargets.length;if(next.messages!==previous)await loadMessages(true);const live=$('#liveStatus');if(live)live.textContent='实时监听 · '+new Date().toLocaleTimeString();}catch{}},5000);
    boot().catch(error=>{ $('#auth').classList.remove('hidden');authNotice(error.message,true); });
  </script>
</body>
</html>`;
