import { describe, expect, it } from "vitest";

import { adminPage } from "./ui.js";

describe("adminPage", () => {
  it("内联管理脚本可以被浏览器正常解析", () => {
    const script = adminPage.match(/<script>([\s\S]*?)<\/script>/)?.[1];
    expect(script).toBeTruthy();
    expect(() => new Function(script || "")).not.toThrow();
  });

  it("个人版不再暴露注册或用户管理，并给手动刷新明确反馈", () => {
    expect(adminPage).not.toContain('data-auth="register"');
    expect(adminPage).not.toContain('data-page="users"');
    expect(adminPage).not.toContain("/api/admin/");
    expect(adminPage).toContain("刷新中…");
    expect(adminPage).toContain("收件箱已刷新，当前没有新消息。");
    expect(adminPage).toContain("history.pushState");
    expect(adminPage).toContain("pageFromLocation");
    expect(adminPage).toContain("if(activePage!==page)window.scrollTo(0,0)");
    expect(adminPage).toContain("if(changed)notice('')");
    expect(adminPage).toContain("/downloads/knowledge-relay-obsidian.zip");
    expect(adminPage).toContain('class="sync-workspace"');
    expect(adminPage.match(/sync-setup-card sync-module-card/g)).toHaveLength(2);
    expect(adminPage).toContain('class="sync-form-footer wide"');
    expect(adminPage).toContain("安装同步插件");
    expect(adminPage).toContain('id="pluginReleaseTitle"');
    expect(adminPage).toContain("发布插件新版");
    expect(adminPage).toContain('id="openPluginPublisher"');
    expect(adminPage).toContain('id="pluginPublishDialog" class="plugin-publish-dialog"');
    expect(adminPage).not.toContain('id="togglePluginPublisher"');
    expect(adminPage).toContain("/api/plugin-release");
    expect(adminPage).toContain("校验并发布");
    expect(adminPage).not.toContain("知流同步 · v1.2.1");
    expect(adminPage).toContain('id="syncTargetCount"');
    expect(adminPage).toContain('class="sync-empty"');
    expect(adminPage).toContain("Nanobot Skill");
    expect(adminPage).toContain("Nanobot 实际加载的完整 SKILL.md");
    expect(adminPage).toContain("/api/nanobot/provider");
    expect(adminPage).toContain("使用 OpenAI 账户登录");
    expect(adminPage).toContain("providerModelOptions");
    expect(adminPage).toContain("/api/nanobot/provider/models?provider=");
    expect(adminPage).toContain("已获取 ");
    expect(adminPage).toContain('class="agent-workspace"');
    expect(adminPage).toContain(".agent-workspace{display:grid;gap:18px;align-items:stretch}");
    expect(adminPage).toContain('class="model-catalog-bar wide"');
    expect(adminPage).toContain(".provider-field>input,.provider-field>select{height:46px}");
    expect(adminPage).toContain(".head>button,.head>.button-link{flex:0 0 auto;white-space:nowrap}");
    expect(adminPage).not.toContain('class="model-picker"');
    expect(adminPage).toContain('data-page="system"');
    expect(adminPage).toContain('data-view="settings"');
    expect(adminPage.match(/data-page=/g)).toHaveLength(3);
    expect(adminPage).not.toContain('data-page="home"');
    expect(adminPage).not.toContain('data-page="wechat"');
    expect(adminPage).not.toContain('data-page="agent"');
    expect(adminPage).not.toContain('data-page="skills"');
    expect(adminPage).toContain('class="topbar"');
    expect(adminPage).toContain('class="account-menu"');
    expect(adminPage).toContain('id="settingsContext"');
    expect(adminPage).toContain('class="settings-context-nav"');
    expect(adminPage).toContain('data-target="wechat"');
    expect(adminPage).toContain('data-settings-page="wechat"');
    expect(adminPage).not.toContain('data-settings-page="settings"');
    expect(adminPage).toContain('class="capture-flow"');
    expect(adminPage).toContain("知识收件台");
    expect(adminPage).toContain("primaryPage=inSettings?'system':page");
    expect(adminPage).toContain("个人版 · 独立工作区");
    expect(adminPage).not.toContain('data-view="home"');
    expect(adminPage).not.toContain('class="nav-settings"');
    expect(adminPage).not.toContain("<aside");
    expect(adminPage).not.toContain('class="settings-hub"');
    expect(adminPage).toContain(".topbar{position:sticky");
    expect(adminPage).toContain('class="topbar-inner"');
    expect(adminPage).toContain('id="confirmPassword"');
    expect(adminPage).toContain("newPassword!==confirmPassword");
    expect(adminPage).toContain("/api/me/profile");
    expect(adminPage).toContain('id="aiRuntimeCard"');
    expect(adminPage).toContain('id="aiCategoryBars"');
    expect(adminPage).toContain('id="aiRecentResults"');
    expect(adminPage).toContain("renderIntelligence(result.messages)");
    expect(adminPage).toContain('class="secondary small runtime-test"');
    expect(adminPage).not.toContain('<div class="card section"><h2>账户安全</h2>');
    expect(adminPage).toContain("AI 智能整理");
    expect(adminPage).toContain("选择模型服务并设置整理偏好");
    expect(adminPage).not.toContain("不会绕过 Runtime 直连模型");
    expect(adminPage).not.toContain("Agent Runtime / Control Plane");
    expect(adminPage).not.toContain("保存并重新加载 Runtime");
    expect(adminPage).toContain("整理方式");
    expect(adminPage).toContain("高级连接信息");
    expect(adminPage).toContain('class="list skill-list"');
    expect(adminPage).toContain(".skill-card{position:relative");
    expect(adminPage).not.toContain("核对上游原始 SKILL.md");
  });

  it("滚动路径不使用高开销固定模糊层或悬停位移", () => {
    expect(adminPage).toContain("scrollbar-gutter:stable");
    expect(adminPage).not.toContain("backdrop-filter");
    expect(adminPage).not.toContain("animation:drift");
    expect(adminPage).not.toContain("transform:translateY(-1px)");
    expect(adminPage).toContain("animation:ambient-orbit");
    expect(adminPage).toContain("will-change:transform");
  });
});
