import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const root = new URL("../", import.meta.url);
const read = (path: string) => readFileSync(new URL(path, root), "utf8");

function contrastRatio(foreground: string, background: string): number {
  const luminance = (hex: string) => {
    const channels = hex.slice(1).match(/../g)!.map((channel) => Number.parseInt(channel, 16) / 255).map((channel) => channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
    return 0.2126 * channels[0]! + 0.7152 * channels[1]! + 0.0722 * channels[2]!;
  };
  const values = [luminance(foreground), luminance(background)].sort((left, right) => right - left);
  return (values[0]! + 0.05) / (values[1]! + 0.05);
}

describe("component frontend", () => {
  it("uses an independent React application instead of an inline admin template", () => {
    const app = read("frontend/src/App.tsx");
    const server = read("src/server.ts");
    expect(app).toContain("<Routes>");
    expect(app).toContain('path="/inbox"');
    expect(app).toContain('path="/review"');
    expect(app).toContain('path="/library"');
    expect(app).toContain('path="/knowledge-chat"');
    expect(app).toContain('path="/reader/:id"');
    expect(app).toContain('path="/settings/:section"');
    expect(app).toContain('path="/settings/sources"');
    expect(app).toContain('<Navigate to="/settings/intake" replace />');
    expect(server).toContain("fastifyStatic");
    expect(server).toContain('prefix: "/app/"');
    expect(server).toContain("loadWebIndex");
    expect(server).not.toContain("adminPage");
  });

  it("preserves all core product journeys", () => {
    const inbox = read("frontend/src/pages/InboxPage.tsx");
    expect(inbox).toContain("queryClient.prefetchQuery");
    expect(inbox).toContain("await queryClient.fetchQuery");
    expect(inbox).toContain("placeholderData: keepPreviousData");
    expect(inbox).not.toContain("messagePageMinHeight");
    expect(inbox).toContain("disabled={view.page === 0 || Boolean(pageNavigation)}");
    const library = read("frontend/src/pages/LibraryPage.tsx");
    expect(library).toContain("/api/knowledge/facets?organized=1");
    expect(library).toContain('params.set("format", format)');
    expect(library).toContain('params.set("knowledgePoint", knowledgePoint)');
    expect(library).toContain('params.set("tool", tool)');
    expect(library).toContain("knowledge-relay-library-view");
    expect(library).not.toContain('active=1&organized=1');
    expect(library).toContain('refetchOnMount: "always"');
    expect(library).toContain("refetchInterval: 20_000");
    expect(library).toContain("const clearFilters = () =>");
    expect(library).toContain("清除筛选并显示全部");
    const reader = read("frontend/src/pages/ReaderPage.tsx");
    expect(reader).toContain("文章正文");
    expect(reader).toContain("智能图解");
    expect(reader).toContain("重新整理");
    expect(reader).toContain("永久删除");
    expect(reader).toContain("ReactMarkdown");
    expect(reader).toContain('attachment.kind === "derived" && attachment.mimeType === "text/markdown"');
    expect(reader).toContain('["article-markdown", messageId, articleAttachment?.id]');
    expect(reader).toContain("normalizeReadingMarkdown(children).replace(/attachment:");
    expect(reader).toContain("attachment.sha256.toLowerCase() === hash.toLowerCase()");
    expect(reader).toContain('className="prose-table-scroll"');
    expect(reader).toContain('className="prose-code-block"');
    expect(reader).toContain('"prose-media-link"');
    expect(reader).toContain('className="prose-image-shell is-unavailable"');
    expect(reader).not.toContain("article-image-strip");
    expect(reader).not.toContain("rehypeRaw");
    expect(read("frontend/src/markdown.ts")).toContain('from "../../src/markdown"');
    const diagram = read("frontend/src/components/KnowledgeDiagram.tsx");
    expect(diagram).toContain('addEventListener("wheel", handleWheel, { passive: false })');
    expect(diagram).toContain("setPointerCapture");
    expect(diagram).toContain("适配窗口");
    expect(diagram).toContain("maximumScale = 2.5");
    expect(diagram).toContain("ResizeObserver");
    expect(diagram).toContain('closest(".diagram-node")');
    expect(diagram).toContain("event.stopPropagation(); selectNode(node.id, event.currentTarget)");
    expect(diagram).toContain("diagram-node-card");
    expect(diagram).toContain("roleNames");
    const settings = read("frontend/src/pages/SettingsPage.tsx");
    for (const journey of ["收件接入", "微信 iLink", "开放 API", "AI 智能整理", "整理能力", "用户管理", "账号与安全"]) {
      expect(settings).toContain(journey);
    }
    expect(settings).toContain("/api/admin/invitations");
    expect(settings).toContain("邀请链接（仅显示一次）");
    expect(settings).toContain("创建邀请");
    expect(settings).toContain("重置用户密码");
    expect(settings).toContain("invitationPageSize");
    const knowledgeChat = read("frontend/src/pages/KnowledgeChatPage.tsx");
    expect(knowledgeChat).toContain("不会用网络信息或模型记忆补充事实");
    expect(knowledgeChat).toContain("问答范围");
    expect(knowledgeChat).toContain("回答依据");
    expect(knowledgeChat).toContain("/api/knowledge/chats");
    expect(knowledgeChat).toContain("/messages/stream");
    expect(knowledgeChat).toContain("streamedAnswer");
    expect(knowledgeChat).toContain("持续提问");
    expect(knowledgeChat).toContain("停止生成");
    expect(knowledgeChat).toContain("复制回答");
    expect(knowledgeChat).toContain("chat-progress");
    expect(knowledgeChat).toContain("conversationPreview");
    const styles = read("frontend/src/styles.css");
    for (const rule of [".knowledge-chat-shell {", ".chat-history-panel {", ".chat-history-item > button:first-child {", ".chat-main {", ".chat-transcript {", ".chat-message-content {"]) {
      expect(styles).toContain(rule);
    }
    expect(styles).toContain("-webkit-line-clamp: 2");
    expect(read("frontend/src/components/Layout.tsx")).toContain('to: "/knowledge-chat"');
    expect(read("frontend/src/components/Layout.tsx")).toContain('to: "/review"');
    expect(read("frontend/src/components/Layout.tsx")).toContain('to="/tasks"');
    expect(read("frontend/src/components/Layout.tsx")).toContain('label: "Obsidian 同步"');
    const search = read("frontend/src/components/SearchDialog.tsx");
    expect(search).toContain("随知识库动态变化");
    expect(search).toContain("个人知识检索");
    expect(search).toContain("检索负责定位原文，不代替知识问答生成结论");
    expect(search).toContain("需要归纳、比较或追问？进入知识问答");
    expect(search).not.toContain("基于结果提问");
    expect(search).toContain("activeRequest.current?.abort()");
    expect(search).toContain("dialogRef.current?.querySelectorAll");
    expect(search).toContain("onCloseRef.current()");
    expect(search).toContain("facets.isError");
    expect(search).toContain("matchReasons");
    const auth = read("frontend/src/pages/AuthPage.tsx");
    expect(auth).toContain('new URLSearchParams(window.location.search).get("invite")');
    expect(auth).toContain("defaultValue={initialInviteToken}");
    expect(auth).toContain("把散落在各处的好内容");
    expect(auth).toContain("auth-knowledge-scene");
    expect(read("frontend/src/components/Brand.tsx")).toContain('src="/app/favicon.svg?v=20260905"');
    expect(read("frontend/src/main.tsx")).toContain('addEventListener("vite:preloadError"');
    expect(read("frontend/src/App.tsx")).toContain("lazy(() => import");
    expect(read("frontend/src/App.tsx")).toContain("<Suspense");
    expect(settings).toContain("/api/nanobot/provider/models?provider=");
    expect(settings).toContain("刷新模型列表");
    expect(settings).toContain("检查草稿连接");
    expect(settings).toContain('api<DraftModelConnectionResult>("/api/nanobot/provider/test"');
    expect(settings).toContain("配置尚未保存");
    expect(settings).toContain('api<ModelConnectionResult>("/api/agent/test"');
    expect(settings).toContain("if (result.ok)");
    const obsidian = read("frontend/src/pages/ObsidianPage.tsx");
    expect(obsidian).toContain("/api/sync-targets");
    expect(obsidian).toContain('owner.role === "admin"');
    expect(obsidian).toContain('type="file"');
    expect(obsidian).toContain("/api/plugin-release");
    expect(obsidian).toContain("校验并发布");
    expect(obsidian).toContain("10 * 1024 * 1024");
    expect(settings).toContain("分层路由");
    expect(settings).toContain("新建 Skill");
    expect(settings).toContain('api("/api/skills", { method: "POST"');
    expect(diagram).toContain("在图解中查找");
    expect(diagram).toContain("diagram-node-panel");
    expect(diagram).toContain("aria-expanded={selectedId === node.id}");
    expect(diagram).toContain("handleStageKeyDown");
    expect(diagram).toContain("stageRef.current.getBoundingClientRect()");
    expect(reader).toContain("后台任务不会中断");
    expect(reader).toContain("暂时无法读取图解状态");
    expect(reader).toContain("diagram.data?.status === \"generating\"");
    expect(read("frontend/src/components/KnowledgeRelay.tsx")).toContain("正在保存并缓存");
    const review = read("frontend/src/pages/ReviewPage.tsx");
    expect(review).toContain("今天值得重看的内容");
    expect(review).toContain("一周后提醒");
    expect(reader).toContain("标注选中文字");
    expect(reader).toContain("阅读标注已保存");
    expect(reader).toContain("版本记录");
    expect(reader).toContain("文章目录");
    expect(reader).toContain("内容完整性");
    expect(library).toContain("保存为智能集合");
    expect(library).toContain("/api/collections");
    expect(settings).toContain("内容质量");
    expect(settings).toContain("数据与备份");
    expect(settings).toContain("/api/account/export");
    expect(settings).toContain("自动来源");
    expect(settings).toContain("/api/feed-sources");
    expect(settings).toContain("来源检查已进入任务中心");
  });

  it("uses a high-contrast reading system without blurred glass surfaces", () => {
    const styles = read("frontend/src/styles.css");
    expect(styles).toContain("--text: #171824");
    expect(styles).toContain("--surface: #fffefd");
    expect(styles).toContain("body { margin: 0; min-width: 320px; min-height: 100vh; background: var(--canvas); color: var(--text); font-size: 15px;");
    expect(styles).toContain("font-size: 18px");
    expect(styles).toContain("line-height: 1.78");
    expect(styles).toContain(".prose-table-scroll");
    expect(styles).toContain(".prose-code-block");
    expect(styles).toContain(".prose a.prose-media-link");
    expect(styles).toContain(".prose-media-link .prose-image-shell img");
    expect(styles).toContain(".reader-tabs { position: static;");
    expect(styles).not.toContain(".reader-tabs { position: sticky;");
    expect(read("frontend/src/components/KnowledgeRelay.tsx")).toContain('"捕获"');
    expect(read("frontend/src/components/KnowledgeRelay.tsx")).toContain("语义整理引擎");
    expect(styles).toContain("@keyframes relay-packet-in");
    expect(styles).toContain("@keyframes relay-stage-dot");
    expect(styles).toContain("prefers-reduced-motion: reduce");
    expect(styles).toContain("height: calc(100dvh - 76px)");
    expect(styles).toContain(".stream-caret");
    expect(styles).toContain(".reading-progress");
    expect(styles).toContain(".reader-toc");
    expect(styles).not.toContain("backdrop-filter");
    expect(styles).not.toContain("@import url(");
  });

  it("supports persistent light and dark themes with settings in the product navigation", () => {
    const app = read("frontend/src/App.tsx");
    const main = read("frontend/src/main.tsx");
    const layout = read("frontend/src/components/Layout.tsx");
    const settings = read("frontend/src/pages/SettingsPage.tsx");
    const styles = read("frontend/src/styles.css");
    expect(app).toContain('type Theme = "light" | "dark"');
    expect(main).toContain("prefers-color-scheme: dark");
    expect(main).toContain("knowledge-relay-theme");
    expect(layout).toContain("theme-toggle");
    expect(layout).toContain("workspace-masthead");
    expect(layout).toContain("primary-navigation");
    expect(layout).toContain("contextual-navigation");
    expect(layout).toContain("navigation-drawer");
    expect(layout).not.toContain("sidebarCollapsed");
    expect(styles).toContain(".workspace-masthead");
    expect(styles).toContain(".contextual-navigation");
    expect(layout).toContain('to="/settings/intake"');
    expect(layout).not.toContain('to="/settings/api"');
    expect(read("frontend/src/pages/InboxPage.tsx")).toContain("<span>内容来源</span>");
    expect(settings).not.toContain("settings-nav");
    expect(styles).toContain(':root[data-theme="dark"]');
    expect(styles).toContain("--text: #f7f5f2");
    expect(styles).toContain("--text-secondary: #d5d2dc");
    expect(styles).toContain("--text-muted: #a8a5b2");
    expect(styles).toContain("--text-placeholder: #b3b0bd");
    expect(styles).toContain("input::placeholder, textarea::placeholder");
    expect(styles).toContain(".search-form input { width: 100%; min-width: 0;");
    expect(styles).toContain("appearance: none; background: transparent;");
    expect(styles).toContain(':root[data-theme="dark"] body { -webkit-font-smoothing: auto; }');
    expect(styles).toContain(".prose .original-text");
    expect(styles).not.toContain(".settings-shell");
  });

  it("keeps every dark theme text tier above enhanced WCAG contrast", () => {
    const surface = "#151721";
    expect(contrastRatio("#f7f5f2", surface)).toBeGreaterThanOrEqual(7);
    expect(contrastRatio("#d5d2dc", surface)).toBeGreaterThanOrEqual(7);
    expect(contrastRatio("#a8a5b2", surface)).toBeGreaterThanOrEqual(7);
    expect(contrastRatio("#b3b0bd", surface)).toBeGreaterThanOrEqual(7);
    expect(contrastRatio("#b0aaff", surface)).toBeGreaterThanOrEqual(7);
  });
});
