import { describe, expect, it } from "vitest";

import { adminPage } from "./ui.js";

describe("adminPage", () => {
  it("内联管理脚本可以被浏览器正常解析", () => {
    const script = adminPage.match(/<script>([\s\S]*?)<\/script>/)?.[1];
    expect(script).toBeTruthy();
    expect(() => new Function(script || "")).not.toThrow();
  });

  it("多用户入驻、资源管理和手动刷新都有明确交互", () => {
    expect(adminPage).not.toContain('data-auth="register"');
    expect(adminPage).not.toContain('data-page="users"');
    expect(adminPage).toContain("/api/admin/users");
    expect(adminPage).toContain("/api/register");
    expect(adminPage).toContain("用户与工作区");
    expect(adminPage).toContain("/api/admin/users/'+encodeURIComponent(statusButton.dataset.userStatus)+'/status");
    expect(adminPage).toContain("/api/admin/users/'+encodeURIComponent(deleteButton.dataset.userDelete)");
    expect(adminPage).toContain('id="userSearch"');
    expect(adminPage).toContain("API 收件");
    expect(adminPage).toContain("/api/me/api-tokens");
    expect(adminPage).toContain("data-resource-view");
    expect(adminPage).not.toContain("['favorites','收藏']");
    expect(adminPage).toContain("/api/knowledge/map");
    expect(adminPage).toContain("复制 Mermaid");
    expect(adminPage).toContain("下载 Mermaid");
    expect(adminPage).toContain("下载 Canvas");
    expect(adminPage).toContain("下载 SVG");
    expect(adminPage).toContain("flowchart TB");
    expect(adminPage).toContain("function mindMapCanvas");
    expect(adminPage).toContain("'.canvas'");
    expect(adminPage).toContain('class="map-export-menu"');
    expect(adminPage).toContain("currentAttachmentByHash");
    expect(adminPage).toContain('class="resource-figure-button"');
    expect(adminPage).toContain('loading="lazy" decoding="async"');
    expect(adminPage).toContain('data-map-action="out"');
    expect(adminPage).toContain('data-map-action="fit"');
    expect(adminPage).toContain("addEventListener('wheel'");
    expect(adminPage).toContain("addEventListener('pointermove'");
    expect(adminPage).toContain("new ResizeObserver");
    expect(adminPage).toContain("resourceFetchController?.abort()");
    expect(adminPage).toContain("网页仅展示前 3 MB");
    expect(adminPage).toContain('class="resource-mobile-nav"');
    expect(adminPage).toContain('data-resource-mobile="reader"');
    expect(adminPage).toContain('data-resource-mobile="map"');
    expect(adminPage).toContain("routeFromLocation().resourceId");
    expect(adminPage).toContain("'#reader/'+encodeURIComponent(id)");
    expect(adminPage).toContain("/reprocess");
    expect(adminPage).toContain("刷新中…");
    expect(adminPage).toContain("已是最新，没有发现新消息。");
    expect(adminPage).toContain('const UI_BUILD = "1.9.0"');
    expect(adminPage).toContain('data-page="library"');
    expect(adminPage).toContain('data-view="library"');
    expect(adminPage).toContain('把稍后再看，变成随时能找到');
    expect(adminPage).toContain('微信公众号文章');
    expect(adminPage).toContain("params.set('format',category)");
    expect(adminPage).toContain('class="card library-explore"');
    expect(adminPage).toContain('AI DYNAMIC TOPICS');
    expect(adminPage).toContain('更多主题 · ');
    expect(adminPage).toContain('data-library-topic');
    expect(adminPage).toContain('data-library-type');
    expect(adminPage).toContain("params.set('domain',domain)");
    expect(adminPage).toContain("organized:'1'");
    expect(adminPage).toContain('/api/knowledge/facets?organized=1&limit=60');
    expect(adminPage).toContain('library-card-cover');
    expect(adminPage).toContain('.reader-page .resource-reader>h1:first-child{display:none}');
    expect(adminPage).toContain("x-knowledge-relay-ui");
    expect(adminPage).toContain("每页显示 10 条");
    expect(adminPage).toContain('id="previousMessages"');
    expect(adminPage).toContain('id="nextMessages"');
    expect(adminPage).toContain("new URLSearchParams({limit:'10'})");
    expect(adminPage).toContain("'/api/messages?'+params.toString()");
    expect(adminPage).toContain("检索个人知识");
    expect(adminPage).toContain("Nanobot 正在理解检索需求");
    expect(adminPage).toContain("正在匹配该分类下的收件内容");
    expect(adminPage).toContain("nanobot_planned_search");
    expect(adminPage).toContain("按出现频次稳定展示每类前 10 项");
    expect(adminPage).toContain("count.textContent=actualTotal>facets.length?'高频 '");
    expect(adminPage).toContain("textual=mime.startsWith('text/')");
    expect(adminPage).toContain('id="messageDialog" class="resource-dialog"');
    expect(adminPage).toContain("page.dataset.view='reader'");
    expect(adminPage).toContain("page.querySelector('.page-kicker').textContent='Knowledge / Reading'");
    expect(adminPage).toContain("categoryFacets=facets.categories||[]");
    expect(adminPage).toContain("全库分类分布");
    expect(adminPage).toContain("正文图片已本地保存");
    expect(adminPage).toContain("当前页面会保留，并在完成后自动载入新版");
    expect(adminPage).not.toContain("notice('已重新提交给 Nanobot，完成后会自动刷新。');$('#messageDialog').close()");
    expect(adminPage).toContain('id="resourceReader"');
    expect(adminPage).toContain('id="resourceMapStage"');
    expect(adminPage).toContain("reader.innerHTML=renderMarkdown(documentItem.content)");
    expect(adminPage).toContain("attachmentIsText");
    expect(adminPage).not.toContain("只查找你的收件内容");
    expect(adminPage).not.toContain("不会联网、执行命令、修改或删除数据");
    expect(adminPage).toContain("white-space:nowrap");
    expect(adminPage).toContain("#globalNotice{position:fixed");
    expect(adminPage).not.toContain("background:#102d23;color:#7ae7ba");
    expect(adminPage).toContain("history.pushState");
    expect(adminPage).toContain("pageFromLocation");
    const initialRoute = adminPage.indexOf("async function showApp(){const initialRoute=routeFromLocation()");
    const revealApp = adminPage.indexOf("$('#app').classList.remove('hidden')", initialRoute);
    const initialRefresh = adminPage.indexOf("await refreshAll()", revealApp);
    expect(initialRoute).toBeGreaterThan(-1);
    expect(revealApp).toBeGreaterThan(initialRoute);
    expect(initialRefresh).toBeGreaterThan(revealApp);
    expect(adminPage).toContain("if(changed)window.scrollTo(0,0)");
    expect(adminPage).toContain("document.startViewTransition(()=>{render();finish()})");
    expect(adminPage).toContain("pageTransition.skipTransition()");
    expect(adminPage).toContain("prefers-reduced-motion: reduce");
    expect(adminPage).toContain("Knowledge relay network: source packets converge, organize and leave as reusable knowledge");
    expect(adminPage).toContain('class="ai-relay-svg"');
    expect(adminPage).toContain('class="relay-node relay-node-output"');
    expect(adminPage).toContain('class="relay-packet relay-packet-fast"');
    expect(adminPage).toContain("@keyframes relay-path-drift");
    expect(adminPage).not.toContain('<span class="ai-core-stream"></span>');
    expect(adminPage).toContain("view-transition-name:page-content");
    expect(adminPage).toContain("::view-transition-new(page-content)");
    expect(adminPage).toContain("current.classList.add('page-leaving')");
    expect(adminPage).toContain("pageFallbackTimer=setTimeout");
    expect(adminPage).toContain("void view.offsetWidth;view.classList.add('page-entering')");
    expect(adminPage).toContain("@keyframes page-fade-in{from{opacity:.08}to{opacity:1}}");
    expect(adminPage).not.toContain("translateY(12px)");
    expect(adminPage).not.toContain("translateY(-7px)");
    expect(adminPage).toContain("if(changed)notice('')");
    expect(adminPage).toContain("/downloads/knowledge-relay-obsidian.zip");
    expect(adminPage).toContain('class="sync-workspace"');
    expect(adminPage.match(/sync-setup-card sync-module-card/g)).toHaveLength(2);
    expect(adminPage).toContain('class="sync-form-footer wide"');
    expect(adminPage).toContain("安装同步插件");
    expect(adminPage).toContain('id="pluginReleaseTitle"');
    expect(adminPage).toContain("发布插件新版");
    expect(adminPage).toContain('id="openPluginPublisher"');
    expect(adminPage).toContain('id="pluginPublishDialog" class="plugin-publish-dialog"');
    expect(adminPage).not.toContain('id="togglePluginPublisher"');
    expect(adminPage).toContain("/api/plugin-release");
    expect(adminPage).toContain("校验并发布");
    expect(adminPage).not.toContain("知流同步 · v1.2.1");
    expect(adminPage).toContain('id="syncTargetCount"');
    expect(adminPage).toContain('class="sync-empty"');
    expect(adminPage).toContain("Nanobot Skill");
    expect(adminPage).toContain("执行型 Nanobot Skills");
    expect(adminPage).toContain("收件整理规则");
    expect(adminPage).toContain("Nanobot 实际加载的完整 SKILL.md");
    expect(adminPage).toContain("/api/nanobot/provider");
    expect(adminPage).toContain("使用 OpenAI 账户登录");
    expect(adminPage).toContain("providerModelOptions");
    expect(adminPage).toContain("/api/nanobot/provider/models?provider=");
    expect(adminPage).toContain("已获取 ");
    expect(adminPage).toContain('class="agent-workspace"');
    expect(adminPage).toContain(".agent-workspace{display:grid;gap:18px;align-items:stretch}");
    expect(adminPage).toContain('id="messageMindMap"');
    expect(adminPage).toContain("生成智能图解");
    expect(adminPage).toContain("/api/messages/'+encodeURIComponent(id)+'/diagram");
    expect(adminPage).toContain("重新生成");
    expect(adminPage).toContain("Knowledge / Adaptive diagram");
    expect(adminPage).toContain("function diagramLayout");
    expect(adminPage).toContain("COMPARISON SUBJECTS / 比较对象");
    expect(adminPage).toContain("data.diagramType||'mindmap'");
    expect(adminPage).toContain('class="model-catalog-bar wide"');
    expect(adminPage).toContain(".provider-field>input,.provider-field>select{height:46px}");
    expect(adminPage).toContain(".head>button,.head>.button-link{flex:0 0 auto;white-space:nowrap}");
    expect(adminPage).not.toContain('class="model-picker"');
    expect(adminPage).toContain('data-page="system"');
    expect(adminPage).toContain('data-view="settings"');
    expect(adminPage.match(/data-page=/g)).toHaveLength(3);
    expect(adminPage).not.toContain('data-page="home"');
    expect(adminPage).not.toContain('data-page="wechat"');
    expect(adminPage).not.toContain('data-page="agent"');
    expect(adminPage).not.toContain('data-page="skills"');
    expect(adminPage).toContain('class="topbar"');
    expect(adminPage).toContain('class="account-menu"');
    expect(adminPage).toContain('id="globalSearch"');
    expect(adminPage).toContain('aria-keyshortcuts="Meta+K Control+K"');
    expect(adminPage).toContain('data-query-scope="all"');
    expect(adminPage).toContain('data-query-scope="inbox"');
    expect(adminPage).toContain('data-query-scope="knowledge"');
    expect(adminPage).toContain(".inbox-live-actions #openInboxQuery,.library-hero-actions{display:none}");
    expect(adminPage).toContain("libraryListActions.append($('#libraryListMeta'),$('#libraryRefresh'))");
    expect(adminPage).toContain("Calm ocean shell with a paper reading surface");
    expect(adminPage).toContain(".reader-page .resource-reader{border-color:#d6dee8;background:#f7f8fa;color:#273142");
    expect(adminPage).toContain("Editorial daylight theme: one neutral canvas");
    expect(adminPage).toContain(":root{color-scheme:light;--green:#2f7f89");
    expect(adminPage).toContain("Harmonized intelligence, diagrams and editorial covers");
    expect(adminPage).toContain(".ai-runtime-card{border-color:#d0dbe3;color:#243446");
    expect(adminPage).toContain(".library-card{display:grid;grid-template-rows:170px auto");
    expect(adminPage).toContain(".mindmap-stage,.resource-map-stage{border-color:#cbd7e0");
    expect(adminPage).toContain(".primary,.button-link{color:#fff;background:#3f6173");
    expect(adminPage).toContain(".map-export-menu summary{border-color:#c8d4de");
    expect(adminPage).toContain(".reader-page .resource-dialog-head{border-color:#d2dce4");
    expect(adminPage).toContain(".account-popover .logout-action{color:#974156}");
    expect(adminPage).toContain("Precision polish: editorial surfaces, crisp hierarchy and restrained depth");
    expect(adminPage).toContain("--paper:#fffdfa");
    expect(adminPage).toContain(".topnav button:after{right:15px;bottom:3px;left:15px;height:2px;background:#5f8c92;box-shadow:none}");
    expect(adminPage).toContain(".ai-runtime-card:before{content:\"\"");
    expect(adminPage).toContain(".ai-result-copy strong{color:#213447;font-weight:700}");
    expect(adminPage).toContain(".ai-result-copy span{color:#607286}");
    expect(adminPage).toContain(".category-row{color:#526477}");
    expect(adminPage).toContain(".search-dialog .dialog-body:before{content:\"\"");
    expect(adminPage).toContain(".query-suggestions button{border-color:#cad7de;color:#405d69;background:#eef4f4");
    expect(adminPage).toContain(".query-suggestions button:hover,.query-suggestions button:focus-visible{border-color:#91b2b7");
    expect(adminPage).toContain(".reader-page .resource-reader{border-color:#d4dce2;color:#293648;background:var(--paper)");
    expect(adminPage).toContain(".plugin-file-input::file-selector-button{border-color:#c5d3dc;color:#385363");
    expect(adminPage).toContain(".reader-page .resource-warning{border-color:#e7d1a6;color:#795819;background:#fcf6e8}");
    expect(adminPage).toContain("event.key.toLowerCase()==='k'");
    expect(adminPage).toContain("event.key==='/'");
    expect(adminPage).toContain("if(!$('#inboxQueryDialog').open)$('#inboxQueryDialog').showModal()");
    expect(adminPage).toContain('id="settingsContext"');
    expect(adminPage).toContain('class="settings-context-nav"');
    expect(adminPage).toContain('data-target="wechat"');
    expect(adminPage).toContain('data-settings-page="wechat"');
    expect(adminPage).toContain('data-settings-page="api"');
    expect(adminPage).toContain('data-settings-page="sync"');
    expect(adminPage).toContain('data-view="api"');
    expect(adminPage).toContain('id="apiTokenForm"');
    expect(adminPage).not.toContain('id="manageApiCapture"');
    expect(adminPage).not.toContain('data-settings-page="settings"');
    expect(adminPage).toContain('class="capture-flow"');
    expect(adminPage).toContain("知识收件台");
    expect(adminPage).toContain("primaryPage=inSettings?'system':page==='reader'?'library':page");
    expect(adminPage).toContain("个人版 · 独立工作区");
    expect(adminPage).not.toContain('data-view="home"');
    expect(adminPage).not.toContain('class="nav-settings"');
    expect(adminPage).toContain('class="card library-explore"');
    expect(adminPage).toContain('.reader-page .resource-workspace{box-sizing:border-box;width:min(1040px,100%)');
    expect(adminPage).toContain('.reader-page .resource-main{overflow:visible}');
    expect(adminPage).toContain('.reader-page .resource-document-tabs{z-index:6;gap:8px;margin:0 0 12px;padding:8px;border:1px solid #2d4267;border-radius:14px');
    expect(adminPage).not.toContain('class="settings-hub"');
    expect(adminPage).toContain(".topbar{position:sticky");
    expect(adminPage).toContain('class="topbar-inner"');
    expect(adminPage).toContain('id="confirmPassword"');
    expect(adminPage).toContain("newPassword!==confirmPassword");
    expect(adminPage).toContain("永久删除");
    expect(adminPage).toContain("method:'DELETE'");
    expect(adminPage).toContain("/api/me/profile");
    expect(adminPage).toContain('id="aiRuntimeCard"');
    expect(adminPage).toContain('id="aiCategoryBars"');
    expect(adminPage).toContain('id="aiRecentResults"');
    expect(adminPage).toContain("renderIntelligence(loadedMessages)");
    expect(adminPage).toContain('class="secondary small runtime-test"');
    expect(adminPage).toContain("检查基础连接");
    expect(adminPage).toContain("Nanobot 与模型的基础连接正常。");
    expect(adminPage).not.toContain('<div class="card section"><h2>账户安全</h2>');
    expect(adminPage).toContain("AI 智能整理");
    expect(adminPage).toContain("await loadAgent();notice('整理设置已保存");
    expect(adminPage).toContain("grid-template-columns:minmax(0,1fr);gap:10px;min-width:0;width:100%");
    expect(adminPage).toContain(".message { cursor:pointer;overflow:hidden; }");
    expect(adminPage).toContain("选择模型服务并设置整理偏好");
    expect(adminPage).not.toContain("不会绕过 Runtime 直连模型");
    expect(adminPage).not.toContain("Agent Runtime / Control Plane");
    expect(adminPage).not.toContain("保存并重新加载 Runtime");
    expect(adminPage).toContain("整理方式");
    expect(adminPage).toContain("高级连接信息");
    expect(adminPage).toContain('class="list skill-list"');
    expect(adminPage).toContain(".skill-card{position:relative");
    expect(adminPage).not.toContain("核对上游原始 SKILL.md");
  });

  it("滚动路径不使用高开销固定模糊层或悬停位移", () => {
    expect(adminPage).toContain("scrollbar-gutter:stable");
    expect(adminPage).toContain(".topbar{backdrop-filter:none}");
    expect(adminPage).not.toContain("animation:drift");
    expect(adminPage).not.toContain("transform:translateY(-1px)");
    expect(adminPage).toContain("animation:ambient-orbit");
    expect(adminPage).toContain("will-change:transform");
  });
});
