export const adminPage = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>知流 · Knowledge Relay</title>
  <style>
    :root { color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"PingFang SC",sans-serif;--green:#41e6b2;--cyan:#62c8ff;--ink:#eaf7f2;--muted:#8ea9a0;--line:#203c35;--soft:#102720; }
    * { box-sizing:border-box; } body { margin:0;background:radial-gradient(circle at 80% -20%,#123e45 0,transparent 38%),radial-gradient(circle at 0 80%,#132e27 0,transparent 35%),#07130f;color:var(--ink);min-height:100vh; }
    button,input,textarea { font:inherit; } button { cursor:pointer; } button:disabled { cursor:wait;opacity:.68; }
    .hidden { display:none!important; } .shell { min-height:100vh; display:grid; grid-template-columns:230px 1fr; }
    aside { background:#091914e8;backdrop-filter:blur(24px);border-right:1px solid #203e35;color:white;padding:28px 18px;display:flex;flex-direction:column;gap:24px; }
    .brand { padding:0 10px; }.brand strong { display:block;font-size:22px;letter-spacing:.12em;background:linear-gradient(90deg,var(--green),var(--cyan));-webkit-background-clip:text;color:transparent; }.brand span { color:#71968a;font-size:11px;letter-spacing:.16em;text-transform:uppercase; }
    nav { display:grid; gap:6px; } nav button { text-align:left;border:0;background:transparent;color:#c9ddd4;padding:11px 12px;border-radius:9px; }
    nav button.active,nav button:hover { color:#dffff4;background:linear-gradient(90deg,#41e6b220,#62c8ff0c);box-shadow:inset 2px 0 var(--green); }
    .account { margin-top:auto;padding:12px 10px;border-top:1px solid #ffffff1f;font-size:13px;color:#b8d0c5; }
    main { padding:34px; max-width:1180px; width:100%; } h1 { margin:0;font-size:28px; } h2 { margin:0 0 15px;font-size:19px; } p { line-height:1.65; }
    .head { display:flex;justify-content:space-between;align-items:center;margin-bottom:26px;gap:20px; }
    .muted { color:var(--muted); } .grid { display:grid;grid-template-columns:repeat(4,1fr);gap:14px; }
    .card { background:linear-gradient(145deg,#10241ed9,#0a1a15e8);border:1px solid var(--line);border-radius:15px;padding:20px;box-shadow:0 16px 48px #0007,inset 0 1px #ffffff08;backdrop-filter:blur(18px); }
    .metric { position:relative;overflow:hidden }.metric:after{content:"";position:absolute;width:70px;height:70px;right:-25px;top:-25px;background:var(--green);filter:blur(35px);opacity:.18}.metric strong { display:block;font-size:32px;margin-top:8px;color:var(--green);font-variant-numeric:tabular-nums; }.metric span { color:var(--muted);font-size:12px;letter-spacing:.08em; }
    .section { margin-top:18px; }.row { display:flex;gap:10px;align-items:center;flex-wrap:wrap; }
    .spread { display:flex;justify-content:space-between;gap:12px;align-items:center; }.stack { display:grid;gap:12px; }
    input,textarea { width:100%;border:1px solid #27473d;border-radius:9px;padding:11px 12px;background:#07150f;color:var(--ink); }
    input:focus,textarea:focus{outline:0;border-color:var(--green);box-shadow:0 0 0 3px #41e6b218} textarea { min-height:110px;resize:vertical; } label { display:grid;gap:6px;font-size:13px;color:#91afa4; }
    .check { display:flex;align-items:center;gap:8px; }.check input { width:auto; }
    .primary,.secondary,.danger,.button-link { border:0;border-radius:9px;padding:10px 15px; }
    .primary { color:#04110c;background:linear-gradient(135deg,var(--green),#5bd6e9);font-weight:700;box-shadow:0 8px 22px #41e6b225 }.secondary { color:#cfe8df;background:#17342b; }.danger { color:#ffaaa3;background:#49221f; }
    .small { padding:7px 10px;font-size:13px; }.pill { border-radius:99px;padding:4px 8px;font-size:11px;background:#17342b;color:#9bbcaf;border:1px solid #25463b }.pill.ok { background:#103b2c;color:#55e6a8;border-color:#23704f }.pill.warn { background:#433716;color:#f3cf63;border-color:#6c5924 }
    .button-link{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;color:#04110c;background:linear-gradient(135deg,var(--green),#5bd6e9);font-weight:700;box-shadow:0 8px 22px #41e6b225}.source-link{color:var(--cyan);text-decoration:none}.source-link:hover{text-decoration:underline}.pipeline{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.pipeline div{padding:12px;border:1px solid #23443a;border-radius:10px;background:#081711}.pipeline strong{display:block;color:var(--green);font-size:12px;margin-bottom:4px}
    .list { display:grid;gap:10px; }.item { padding:15px;border:1px solid var(--line);border-radius:11px;background:#0c1d17cc;transition:.18s ease; }.message { cursor:pointer; }.message:hover { border-color:#3c8d72;transform:translateY(-1px);box-shadow:0 10px 30px #0004 }.message .text { color:#9db8ae;margin-top:8px;white-space:pre-wrap;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden; }
    .empty { text-align:center;padding:44px;color:var(--muted); }.notice { border:1px solid #285344;border-radius:10px;padding:11px 13px;background:#102d23;color:#7ae7ba;margin-bottom:14px;white-space:pre-wrap; }.error { background:#3b1e1c;color:#ffaaa3;border-color:#6c302d }.token { display:block;padding:12px;background:#04100c;color:#79eaba;border:1px solid #244a3c;border-radius:8px;word-break:break-all;font-family:ui-monospace,monospace;font-size:12px; }
    .auth { min-height:100vh;display:grid;place-items:center;padding:22px;background:radial-gradient(circle at 20% 0,#154d42,transparent 42%),radial-gradient(circle at 90% 80%,#143348,transparent 38%),#06110d; }.auth .card { width:min(440px,100%);padding:30px; }.tabs { display:flex;gap:5px;background:var(--soft);padding:4px;border-radius:10px;margin-bottom:20px; }.tabs button { flex:1;border:0;background:transparent;color:var(--muted);padding:8px;border-radius:7px; }.tabs button.active { background:#17372d;color:var(--ink);box-shadow:0 2px 8px #0004; }
    dialog { width:min(760px,92vw);border:1px solid #2d5145;border-radius:15px;padding:0;background:#0a1a15;color:var(--ink);box-shadow:0 26px 100px #000b; } dialog::backdrop { background:#020906cc;backdrop-filter:blur(5px) }.dialog-body { padding:24px; }.markdown { white-space:pre-wrap;background:#06120e;padding:14px;border:1px solid #1d382f;border-radius:9px;max-height:45vh;overflow:auto;font:13px/1.6 ui-monospace,monospace; }
    .sync-live{display:inline-flex;align-items:center;gap:7px;color:#79a799;font-size:12px}.sync-live:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green)}.attachments{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px;margin-top:14px}.attachment{padding:12px;border:1px solid #25453a;border-radius:10px;background:#07150f}.attachment strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attachment-actions{display:flex;gap:7px;margin-top:9px}.attachment-actions a{text-decoration:none}.preview-frame{width:100%;height:min(65vh,680px);border:0;background:white;border-radius:9px;margin-top:12px}.preview-image{display:block;max-width:100%;max-height:65vh;margin:12px auto 0;border-radius:9px}
    #qr { width:280px;height:280px;max-width:75vw;display:block;margin:auto; }
    @media(max-width:800px){.shell{display:block}.shell aside{position:sticky;top:0;z-index:3;padding:12px}.brand,.account{display:none}nav{display:flex;overflow:auto}nav button{white-space:nowrap}main{padding:20px}.grid{grid-template-columns:repeat(2,1fr)}.pipeline{grid-template-columns:repeat(2,1fr)}.head{align-items:flex-start}}
  </style>
</head>
<body>
  <div id="auth" class="auth hidden"><section class="card">
    <h1>知流 · Knowledge Relay</h1><p class="muted" id="authLead">把微信中的碎片，汇入你的知识系统。</p>
    <div id="authNotice"></div>
    <form id="authForm" class="stack">
      <label id="displayLabel" class="hidden">显示名称<input id="displayName" autocomplete="name" /></label>
      <label>密码<input id="password" type="password" minlength="8" autocomplete="current-password" required /></label>
      <button id="authSubmit" class="primary" type="submit">登录</button>
    </form>
  </section></div>

  <div id="app" class="shell hidden">
    <aside><div class="brand"><strong>知流</strong><span>Knowledge Relay</span></div>
      <nav>
        <button data-page="home" class="active">概览</button><button data-page="messages">收件箱</button><button data-page="wechat">微信连接</button><button data-page="sync">Obsidian 同步</button><button data-page="agent">AI Agent</button><button data-page="skills">Skills</button>
      </nav>
      <div class="account"><div id="accountName"></div><button id="logout" class="secondary small" style="margin-top:9px">退出登录</button></div>
    </aside>
    <main>
      <div id="globalNotice"></div>
      <section data-view="home"><div class="head"><div><h1>知识流概览</h1><p class="muted">从微信捕获，经规则或 AI 整理，可靠汇入 Obsidian。</p><span id="liveStatus" class="sync-live">实时监听新消息</span></div><button class="primary" data-go="wechat">连接微信</button></div>
        <div class="grid"><div class="card metric"><span>全部消息</span><strong id="mMessages">0</strong></div><div class="card metric"><span>待同步</span><strong id="mPending">0</strong></div><div class="card metric"><span>微信账号</span><strong id="mBots">0</strong></div><div class="card metric"><span>同步设备</span><strong id="mTargets">0</strong></div></div>
        <div class="card section"><h2>最近消息</h2><div id="recentMessages" class="list"></div></div>
        <div class="card section"><h2>账户安全</h2><form id="passwordForm" class="row"><input id="currentPassword" type="password" minlength="8" placeholder="当前密码" required style="flex:1" /><input id="newPassword" type="password" minlength="8" placeholder="新密码（至少 8 位）" required style="flex:1" /><button class="secondary" type="submit">修改密码</button></form></div>
      </section>
      <section data-view="messages" class="hidden"><div class="head"><div><h1>知识收件箱</h1><p class="muted">“已归档”表示主 Obsidian 设备已经确认写入成功。</p><span id="messagesLive" class="sync-live">自动刷新中</span></div><button id="refreshMessages" class="secondary">立即刷新</button></div><div id="messagesList" class="list"></div></section>
      <section data-view="wechat" class="hidden"><div class="head"><div><h1>微信连接</h1><p class="muted">连接你自己的 iLink Bot，知流只接收扫码账号本人的消息。</p></div><button id="connectWechat" class="primary">添加微信</button></div><div id="accountsList" class="list"></div></section>
      <section data-view="sync" class="hidden"><div class="head"><div><h1>Obsidian 同步</h1><p class="muted">为每个 Vault 创建设备令牌。令牌只显示一次，请复制到插件设置。</p></div></div>
        <div class="card"><div class="spread"><div><h2>知流同步插件</h2><p class="muted">下载后解压到 Vault 的 .obsidian/plugins/wechat-ilink-inbox-sync，并在 Obsidian 中启用。</p></div><a class="button-link" href="/downloads/knowledge-relay-obsidian.zip" download>下载插件</a></div></div>
        <div class="card"><h2>创建同步设备</h2><form id="syncForm" class="stack"><label>设备或 Vault 名称<input id="syncName" value="我的 Obsidian" required /></label><label>默认收件箱目录<input id="syncFolder" value="Inbox/微信" required /></label><label class="check"><input id="syncPrimary" type="checkbox" checked />作为主同步设备</label><button class="primary" type="submit">生成连接令牌</button></form><div id="syncTokenResult" class="hidden" style="margin-top:14px"><p>请立即复制，离开页面后无法再次查看：</p><code id="syncToken" class="token"></code></div></div>
        <div class="card section"><h2>已连接设备</h2><div id="targetsList" class="list"></div></div>
      </section>
      <section data-view="agent" class="hidden"><div class="head"><div><h1>智能处理引擎</h1><p class="muted">支持 Nanobot 或 OpenAI 兼容模型，用于理解、分类和生成笔记；关闭时仍能原样同步。</p></div><button id="testAgent" class="secondary">测试连接</button></div>
        <div class="card"><div class="pipeline"><div><strong>01 捕获</strong>接收微信原消息</div><div><strong>02 安全解析</strong>按 Skill 读取网页</div><div><strong>03 AI 整理</strong>分类、摘要、模板内容</div><div><strong>04 同步</strong>笔记与附件进入 Obsidian</div></div><form id="agentForm" class="stack" style="margin-top:18px"><label class="check"><input id="agentEnabled" type="checkbox" />启用 AI 处理</label><label>接口地址（由服务配置）<input id="agentBaseUrl" readonly /></label><label>模型<input id="agentModel" placeholder="例如 deepseek-v4-flash" /></label><label>API Key（留空则保持原值）<input id="agentKey" type="password" /></label><label>默认处理规则<textarea id="agentInstructions" placeholder="例如：所有网页先总结；包含日期的内容提取为待办。"></textarea></label><label class="check"><input id="agentReply" type="checkbox" />允许 Agent 自动回复普通消息</label><label class="check"><input id="agentFailureNotify" type="checkbox" checked />模型失效时通过当前微信消息提醒（同类故障 6 小时内只提醒一次）</label><button class="primary" type="submit">保存设置</button></form></div>
      </section>
      <section data-view="skills" class="hidden"><div class="head"><div><h1>Skills</h1><p class="muted">“可执行适配器”会真正抓取和清洗网页；“提示规则”会改变之后新消息的 AI 整理方式。开关立即生效，不追溯旧消息。</p></div><button id="newSkill" class="primary">新增提示规则</button></div><div id="skillsList" class="list"></div></section>
    </main>
  </div>

  <dialog id="messageDialog"><div class="dialog-body"><div class="spread"><h2 id="dialogTitle"></h2><button class="secondary small" data-close>关闭</button></div><div id="dialogMeta" class="muted"></div><pre id="dialogMarkdown" class="markdown"></pre><div id="dialogAttachments" class="attachments"></div></div></dialog>
  <dialog id="previewDialog"><div class="dialog-body"><div class="spread"><h2 id="previewTitle">附件预览</h2><button class="secondary small" data-close>关闭</button></div><div id="previewBody"></div></div></dialog>
  <dialog id="qrDialog"><div class="dialog-body"><div class="spread"><h2>连接微信</h2><button class="secondary small" data-close>关闭</button></div><img id="qr" alt="微信登录二维码" /><p id="qrStatus" style="text-align:center">请用微信扫码并在手机上确认。</p><div id="pairWrap" class="row hidden"><input id="pairCode" inputmode="numeric" placeholder="输入微信显示的配对码" /><button id="submitPair" class="primary">提交</button></div></div></dialog>
  <dialog id="skillDialog"><div class="dialog-body"><div class="spread"><h2 id="skillDialogTitle">编辑 Skill</h2><button class="secondary small" data-close>关闭</button></div><form id="skillForm" class="stack"><input id="skillId" type="hidden" /><label>名称<input id="skillName" maxlength="80" required /></label><label id="skillSlugLabel">标识<input id="skillSlug" maxlength="60" placeholder="例如 my-inbox-rule" required /></label><label>用途说明<textarea id="skillDescription" maxlength="500" required style="min-height:70px"></textarea></label><label>Skill 规则<textarea id="skillContent" maxlength="20000" required style="min-height:260px"></textarea></label><label class="check"><input id="skillEnabled" type="checkbox" checked />启用这个 Skill</label><div class="row"><button class="primary" type="submit">保存</button><button id="deleteSkill" class="danger hidden" type="button">删除</button></div></form></div></dialog>

  <script>
    const $ = (selector) => document.querySelector(selector);
    const $$ = (selector) => Array.from(document.querySelectorAll(selector));
    let owner = null, dashboard = null, needsSetup = false, loginSession = null, polling = false, managedSkills = [], latestMessageSeq = 0, messageRefresh = null;
    function escapeHtml(value) { const span=document.createElement('span');span.textContent=String(value==null?'':value);return span.innerHTML; }
    async function api(url, options) {
      const response = await fetch(url, Object.assign({ headers: {} }, options || {}, { headers: Object.assign({}, options && options.headers || {}, options && options.body ? {'Content-Type':'application/json'} : {}) }));
      const text = await response.text(); let data={}; try { data=text?JSON.parse(text):{}; } catch { data={error:text}; }
      if (!response.ok) throw new Error(data.error || ('请求失败：'+response.status)); return data;
    }
    function notice(message, error) { $('#globalNotice').innerHTML=message?'<div class="notice '+(error?'error':'')+'">'+escapeHtml(message)+'</div>':''; }
    function authNotice(message, error) { $('#authNotice').innerHTML=message?'<div class="notice '+(error?'error':'')+'">'+escapeHtml(message)+'</div>':''; }
    function configureAuth(setup) { needsSetup=setup;$('#displayLabel').classList.toggle('hidden',!setup);$('#authLead').textContent=setup?'首次使用，请设置个人账户。':'把微信中的碎片，汇入你的知识系统。';$('#authSubmit').textContent=setup?'创建个人账户':'登录'; }
    async function boot() {
      const bootstrap=await api('/api/bootstrap');
      try { const me=await api('/api/me'); owner=me.owner; showApp(); } catch { $('#auth').classList.remove('hidden');configureAuth(bootstrap.needsSetup); }
    }
    $('#authForm').addEventListener('submit',async event=>{event.preventDefault();authNotice('');try{const body=JSON.stringify({password:$('#password').value,displayName:$('#displayName').value});const result=await api(needsSetup?'/api/setup':'/api/login',{method:'POST',body});owner=result.owner;$('#auth').classList.add('hidden');showApp();if(result.migrated&&(result.migrated.account||result.migrated.messages))notice('已自动导入原有微信账号和 '+result.migrated.messages+' 条历史消息。');}catch(error){authNotice(error.message,true)}});
    const validPages=['home','messages','wechat','sync','agent','skills'];
    function pageFromLocation(){const page=location.hash.replace(/^#/,'');return validPages.includes(page)?page:'home';}
    async function showApp(){ $('#app').classList.remove('hidden');$('#accountName').textContent=owner.displayName+' · 个人版';await refreshAll();go(pageFromLocation(),false); }
    async function refreshAll(){ try{dashboard=await api('/api/dashboard');$('#mMessages').textContent=dashboard.messages;$('#mPending').textContent=dashboard.pendingSync;$('#mBots').textContent=dashboard.botAccounts;$('#mTargets').textContent=dashboard.syncTargets.length;renderAccounts();renderTargets();await loadMessages(true);loadAgent();loadSkills();}catch(error){notice(error.message,true)} }
    function go(page,updateLocation=true){if(!validPages.includes(page))page='home';if(updateLocation&&location.hash!=='#'+page)history.pushState(null,'','#'+page);$$('[data-view]').forEach(v=>v.classList.toggle('hidden',v.dataset.view!==page));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='messages')loadMessages(true);}
    $$('[data-page]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.page)));$$('[data-go]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.go)));
    window.addEventListener('hashchange',()=>go(pageFromLocation(),false));
    $('#logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});
    $('#passwordForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/me/password',{method:'POST',body:JSON.stringify({currentPassword:$('#currentPassword').value,newPassword:$('#newPassword').value})});alert('密码已修改，请使用新密码重新登录。');location.reload();}catch(error){notice(error.message,true)}});
    async function loadMessages(silent){if(messageRefresh){await messageRefresh;if(!silent){$('#messagesLive').textContent='刷新完成 · '+new Date().toLocaleTimeString();notice('收件箱已刷新，当前没有遗漏。');}return;}const button=$('#refreshMessages');if(!silent){button.disabled=true;button.textContent='刷新中…';$('#messagesLive').textContent='正在刷新…';}messageRefresh=(async()=>{const result=await api('/api/messages?limit=100');const newest=result.messages[0]&&result.messages[0].seq||0;const hasNew=latestMessageSeq>0&&newest>latestMessageSeq;latestMessageSeq=Math.max(latestMessageSeq,newest);renderMessages(result.messages);const time=new Date().toLocaleTimeString();$('#messagesLive').textContent=hasNew?'发现新消息 · '+time:silent?'自动刷新中 · '+time:'刷新完成 · '+time;if(!silent)notice(hasNew?'已刷新并发现新消息。':'收件箱已刷新，当前没有新消息。');})().catch(error=>{if(!silent)notice('刷新失败：'+error.message,true);throw error;}).finally(()=>{messageRefresh=null;if(!silent){button.disabled=false;button.textContent='立即刷新';}});await messageRefresh;}
    function messageHtml(message){return '<article class="item message" data-message="'+escapeHtml(message.id)+'"><div class="spread"><strong>'+escapeHtml(message.title)+'</strong><div class="row"><span class="pill">'+escapeHtml(message.category)+'</span><span class="pill '+(message.archived?'ok':'warn')+'">'+(message.archived?'已归档':'待同步')+'</span></div></div><div class="muted">'+new Date(message.receivedAt).toLocaleString()+(message.attachmentCount?' · '+message.attachmentCount+' 个附件':'')+'</div><div class="text">'+escapeHtml(message.text||'（仅附件）')+'</div></article>';}
    function bindMessages(){ $$('[data-message]').forEach(item=>item.addEventListener('click',async()=>{const message=await api('/api/messages/'+encodeURIComponent(item.dataset.message));$('#dialogTitle').textContent=message.title;$('#dialogMeta').textContent=new Date(message.receivedAt).toLocaleString()+' · '+message.agentStatus;$('#dialogMarkdown').textContent=message.markdown;$('#dialogAttachments').innerHTML=(message.attachments||[]).map(a=>'<div class="attachment"><strong title="'+escapeHtml(a.fileName)+'">'+escapeHtml(a.fileName)+'</strong><div class="muted">'+escapeHtml(a.mimeType)+' · '+formatBytes(a.size)+'</div>'+(a.transcript?'<div class="muted">转写：'+escapeHtml(a.transcript)+'</div>':'')+'<div class="attachment-actions">'+(a.previewable?'<button class="secondary small" data-preview="'+a.id+'" data-name="'+escapeHtml(a.fileName)+'" data-mime="'+escapeHtml(a.mimeType)+'">预览</button>':'')+'<a class="secondary small" href="/api/attachments/'+a.id+'?download=1">下载</a></div></div>').join('');$$('[data-preview]').forEach(button=>button.addEventListener('click',()=>openPreview(button.dataset.preview,button.dataset.name,button.dataset.mime)));$('#messageDialog').showModal()})); }
    function formatBytes(value){const n=Number(value)||0;if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB';}
    function openPreview(id,name,mime){const url='/api/attachments/'+encodeURIComponent(id);$('#previewTitle').textContent=name;let html;if(mime.startsWith('image/'))html='<img class="preview-image" src="'+url+'" alt="'+escapeHtml(name)+'" />';else if(mime.startsWith('audio/'))html='<audio controls style="width:100%;margin-top:18px" src="'+url+'"></audio>';else if(mime.startsWith('video/'))html='<video controls class="preview-frame" src="'+url+'"></video>';else html='<iframe class="preview-frame" sandbox src="'+url+'"></iframe>';$('#previewBody').innerHTML=html;$('#previewDialog').showModal();}
    function renderMessages(messages){$('#messagesList').innerHTML=messages.length?messages.map(messageHtml).join(''):'<div class="card empty">还没有消息。连接微信后发一条消息试试。</div>';$('#recentMessages').innerHTML=messages.length?messages.slice(0,5).map(messageHtml).join(''):'<div class="empty">还没有消息</div>';bindMessages();}
    $('#refreshMessages').addEventListener('click',()=>loadMessages(false));
    function renderAccounts(){const accounts=dashboard.accounts;$('#accountsList').innerHTML=accounts.length?accounts.map(a=>'<div class="item spread"><div><strong>'+escapeHtml(a.botId)+'</strong><div class="muted">'+escapeHtml(a.ownerUserId||'未知微信用户')+' · '+(a.lastMessageAt?'最近消息 '+new Date(a.lastMessageAt).toLocaleString():'尚未收到消息')+'</div>'+(a.lastError?'<div class="muted">'+escapeHtml(a.lastError)+'</div>':'')+'</div><div class="row"><span class="pill '+(a.state==='running'?'ok':'warn')+'">'+escapeHtml(a.state==='running'?'接收中':a.state)+'</span><button class="danger small" data-remove-account="'+a.id+'">移除</button></div></div>').join(''):'<div class="card empty">尚未连接微信，请扫描二维码连接自己的机器人。</div>';$$('[data-remove-account]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('确定移除这个微信连接吗？历史消息不会删除。'))return;await api('/api/ilink/accounts/'+b.dataset.removeAccount,{method:'DELETE'});await refreshAll()}));}
    $('#connectWechat').addEventListener('click',async()=>{try{const result=await api('/api/ilink/login/start',{method:'POST'});loginSession=result.sessionId;$('#qr').src='/api/ilink/login/'+loginSession+'/qr.svg?x='+Date.now();$('#qrStatus').textContent='请用微信扫码并在手机上确认。';$('#pairWrap').classList.add('hidden');$('#qrDialog').showModal();pollLogin();}catch(error){notice(error.message,true)}});
    async function pollLogin(code){if(polling||!loginSession)return;polling=true;try{const result=await api('/api/ilink/login/'+loginSession+(code?'/verify':'/status'),code?{method:'POST',body:JSON.stringify({code})}:undefined);$('#qrStatus').textContent=result.message;$('#pairWrap').classList.toggle('hidden',result.status!=='need_verifycode');if(result.connected){$('#qrDialog').close();loginSession=null;await refreshAll();notice('微信连接成功，消息接收已经启动。');return;}if(result.status==='need_verifycode')return;if(['expired','error','verify_code_blocked','already_connected'].includes(result.status)){loginSession=null;return;}setTimeout(()=>pollLogin(),1000);}catch(error){$('#qrStatus').textContent=error.message;loginSession=null;}finally{polling=false}}
    $('#submitPair').addEventListener('click',()=>{const code=$('#pairCode').value.trim();if(code)pollLogin(code)});
    function renderTargets(){const targets=dashboard.syncTargets;$('#targetsList').innerHTML=targets.length?targets.map(t=>'<div class="item spread"><div><strong>'+escapeHtml(t.name)+'</strong> '+(t.primary?'<span class="pill ok">主设备</span>':'')+'<div class="muted">'+escapeHtml(t.folder)+' · 游标 '+t.lastAckSeq+(t.lastSeenAt?' · 最近同步 '+new Date(t.lastSeenAt).toLocaleString():'')+'</div></div><button class="danger small" data-revoke="'+t.id+'">撤销</button></div>').join(''):'<div class="empty">还没有 Obsidian 同步设备</div>';$$('[data-revoke]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('撤销后，这个插件将不能再同步。'))return;await api('/api/sync-targets/'+b.dataset.revoke,{method:'DELETE'});await refreshAll()}));}
    $('#syncForm').addEventListener('submit',async event=>{event.preventDefault();try{const result=await api('/api/sync-targets',{method:'POST',body:JSON.stringify({name:$('#syncName').value,folder:$('#syncFolder').value,primary:$('#syncPrimary').checked})});$('#syncToken').textContent=result.token;$('#syncTokenResult').classList.remove('hidden');await refreshAll();}catch(error){notice(error.message,true)}});
    async function loadAgent(){const s=await api('/api/agent/settings');$('#agentEnabled').checked=s.enabled;$('#agentBaseUrl').value=s.baseUrl;$('#agentModel').value=s.model;$('#agentKey').value='';$('#agentKey').placeholder=s.apiKey?'已保存或由服务提供':'可留空';$('#agentInstructions').value=s.instructions;$('#agentReply').checked=s.autoReply;$('#agentFailureNotify').checked=s.notifyOnFailure!==false;}
    $('#agentForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/agent/settings',{method:'PUT',body:JSON.stringify({enabled:$('#agentEnabled').checked,baseUrl:$('#agentBaseUrl').value,model:$('#agentModel').value,apiKey:$('#agentKey').value,instructions:$('#agentInstructions').value,autoReply:$('#agentReply').checked,notifyOnFailure:$('#agentFailureNotify').checked})});notice('AI 处理设置已保存，之后的新消息会使用它。');}catch(error){notice(error.message,true)}});
    $('#testAgent').addEventListener('click',async()=>{try{const result=await api('/api/agent/test',{method:'POST'});notice(result.ok?'AI 模型连接正常。':'连接失败：'+result.error,!result.ok)}catch(error){notice(error.message,true)}});
    async function loadSkills(){const result=await api('/api/skills');managedSkills=result.skills;$('#skillsList').innerHTML=managedSkills.length?managedSkills.map(s=>'<article class="item"><div class="spread"><div><div class="row"><strong>'+escapeHtml(s.name)+'</strong><span class="pill">'+(s.kind==='adapter'?'可执行适配器':s.builtin?'内置提示规则':'自定义提示规则')+'</span>'+(s.customized?'<span class="pill warn">已修改</span>':'')+'<span class="pill '+(s.enabled?'ok':'')+'">'+(s.enabled?'已启用':'已停用')+'</span></div><div class="muted">'+escapeHtml(s.description)+'</div><code>'+escapeHtml(s.slug)+'</code>'+(s.sourceUrl?'<div><a class="source-link" target="_blank" rel="noopener noreferrer" href="'+escapeHtml(s.sourceUrl)+'">查看固定来源</a> · <span class="muted">'+escapeHtml((s.sourceRevision||'').slice(0,12))+'</span></div>':'')+'</div><div class="row"><button class="secondary small" data-skill-toggle="'+escapeHtml(s.id)+'">'+(s.enabled?'停用':'启用')+'</button><button class="secondary small" data-skill-edit="'+escapeHtml(s.id)+'">编辑规则</button></div></div></article>').join(''):'<div class="card empty">还没有 Skill</div>';$$('[data-skill-edit]').forEach(b=>b.addEventListener('click',()=>openSkill(managedSkills.find(s=>s.id===b.dataset.skillEdit))));$$('[data-skill-toggle]').forEach(b=>b.addEventListener('click',async()=>{const s=managedSkills.find(x=>x.id===b.dataset.skillToggle);await api('/api/skills/'+encodeURIComponent(s.id),{method:'PUT',body:JSON.stringify({name:s.name,description:s.description,content:s.content,enabled:!s.enabled})});await loadSkills();notice((!s.enabled?'已启用：':'已停用：')+s.name+'。只影响之后收到的新消息。')}));}
    function openSkill(skill){const editing=Boolean(skill);$('#skillDialogTitle').textContent=editing?'编辑 Skill':'新增自定义 Skill';$('#skillId').value=editing?skill.id:'';$('#skillName').value=editing?skill.name:'';$('#skillSlug').value=editing?skill.slug:'';$('#skillSlug').readOnly=editing;$('#skillSlugLabel').classList.toggle('hidden',editing);$('#skillDescription').value=editing?skill.description:'';$('#skillContent').value=editing?skill.content:'';$('#skillEnabled').checked=editing?skill.enabled:true;$('#deleteSkill').classList.toggle('hidden',!editing);if(editing){$('#deleteSkill').textContent=skill.builtin?'恢复系统默认':'删除自定义 Skill';}$('#skillDialog').showModal();}
    $('#newSkill').addEventListener('click',()=>openSkill());
    $('#skillForm').addEventListener('submit',async event=>{event.preventDefault();try{const id=$('#skillId').value;const body=JSON.stringify({slug:$('#skillSlug').value,name:$('#skillName').value,description:$('#skillDescription').value,content:$('#skillContent').value,enabled:$('#skillEnabled').checked});await api(id?'/api/skills/'+encodeURIComponent(id):'/api/skills',{method:id?'PUT':'POST',body});$('#skillDialog').close();await loadSkills();notice('Skill 已保存，之后的新消息会使用最新规则。');}catch(error){notice(error.message,true)}});
    $('#deleteSkill').addEventListener('click',async()=>{const id=$('#skillId').value;if(!id)return;const skill=managedSkills.find(s=>s.id===id);if(!confirm(skill&&skill.builtin?'确定恢复这个系统 Skill 的默认内容和启用状态吗？':'确定删除这个自定义 Skill 吗？'))return;await api('/api/skills/'+encodeURIComponent(skill.builtin?'builtin:'+skill.slug:id),{method:'DELETE'});$('#skillDialog').close();await loadSkills();});
    $$('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
    setInterval(async()=>{if(!owner||document.hidden)return;try{const next=await api('/api/dashboard');const previous=dashboard&&dashboard.messages||0;dashboard=next;$('#mMessages').textContent=next.messages;$('#mPending').textContent=next.pendingSync;$('#mBots').textContent=next.botAccounts;$('#mTargets').textContent=next.syncTargets.length;if(next.messages!==previous)await loadMessages(true);const live=$('#liveStatus');if(live)live.textContent='实时监听 · '+new Date().toLocaleTimeString();}catch{}},5000);
    boot().catch(error=>{ $('#auth').classList.remove('hidden');authNotice(error.message,true); });
  </script>
</body>
</html>`;
